CDAP-13872 add mmds docs
cdapio/cdap pull request #10443
Opened 2018-07-25 04:50 UTC by albertshau

2018-07-25 04:51 UTC, albertshau commented
https://builds.cask.co/browse/CDAP-DQB409

2018-07-25 04:59 UTC, albertshau commented
https://builds.cask.co/artifact/CDAP-DQB409/shared/build-1/Docs-HTML/html/user-guide/mmds/index.html

2018-07-25 07:22 UTC, anwar6953 commented on cdap-docs/_common/_source/guides.rst
> +  - |user-guide-mmds-black|_ Interactive, UI driven analytics and machine learning
should it be `UI-driven`?

2018-07-25 07:24 UTC, anwar6953 commented on cdap-docs/user-guide/source/mmds/concepts.rst
> +together in one place and compare how each of them perform. In the realestate example, all models in the
Should there be a space between "real" and "estate"?
Or are you treating "realestate" as a name of the example?

2018-07-25 07:26 UTC, anwar6953 commented on cdap-docs/user-guide/source/mmds/concepts.rst
> +the training dataset is 80% of the input data and is randomnly chosen. Any data point not in the training dataset
nit - s/randomnly/randomly

2018-07-25 07:28 UTC, anwar6953 commented on cdap-docs/user-guide/source/mmds/concepts.rst
> +Mean absolute error is the average of the error between the prediction and the observed outcome
nit - how come no periods at the end of these definitions, unlike for lines 86-90?

2018-07-25 07:29 UTC, anwar6953 commented on cdap-docs/user-guide/source/mmds/concepts.rst
> +the model. For example, suppose you notice that house price predictions tend to farther off when the number of bedrooms is not known.
"to farther off" --> "to be farther off"

2018-07-25 07:31 UTC, anwar6953 commented on cdap-docs/user-guide/source/mmds/example.rst
> +dollars. Houses in the Bay Area are expensive.
:(

2018-07-25 07:33 UTC, anwar6953 commented on cdap-docs/user-guide/source/mmds/example.rst
> +to the Pipeline Studio with part of a pipeline pre-configured for you. All that is left
nit - preconfigured (without the dash?)

2018-07-25 07:35 UTC, anwar6953 commented on cdap-docs/user-guide/source/mmds/feature-gen.rst
> +In this example, the outcome is price, and the features are city, zip, type, beds, baths, sqft, lot, stories, and year_built.
`lot` --> `lot_sqft`?
You reference the column name as `lot_sqft` in https://github.com/caskdata/cdap/pull/10443/files#diff-f272ee6a7f9e505893c993c6dc040904R42

2018-07-25 07:40 UTC, anwar6953 requested changes
Only had minor comments.
Nice work on having an easy to read and understand guide!

2018-07-25 19:41 UTC, albertshau commented
docs for latest commit, with more example detail https://builds.cask.co/artifact/CDAP-DQB409/shared/build-2/Docs-HTML/html/user-guide/mmds/example.html

2018-07-26 00:00 UTC, deb-saunders commented
Docs reviewed and changes requested as per conversation with albertshau@

2018-07-26 00:11 UTC, albertshau commented
docs after latest build https://builds.cask.co/artifact/CDAP-DQB409/shared/build-3/Docs-HTML/html/user-guide/mmds/index.html

2018-07-26 01:18 UTC, merged