CDAP-13857 Document metadata migration
cdapio/cdap pull request #10454
Opened 2018-07-25 20:49 UTC by CuriousVini

Quick build: https://builds.cask.co/browse/CDAP-DQB420-1

2018-07-26 05:28 UTC, deb-saunders requested changes

2018-07-26 05:28 UTC, deb-saunders commented on cdap-docs/reference-manual/source/http-restful-api/metadata.rst
> +Please note that CDAP will perform online metadata migration when CDAP is migrated from 4.3.x to 5.0.0. When metadata
**Note**: The online metadata is migrated when CDAP migrates from 4.3.x to 5.0.0.  During metadata migration, writes to non-migrated entities fail and reads on metadata for non-migrated entities do not have all the metadata. Metadata migration takes approximately 2-3 minutes. You can check the metadata migration status by using the :ref:`upgrade status <http-restful-api-monitor-status-system-upgrade>` REST endpoint.

GLOBAL: changing to present tense & active voice

2018-07-26 05:28 UTC, deb-saunders commented on cdap-docs/reference-manual/source/http-restful-api/metadata.rst
> +will not have all the metadata. Metadata migration is expected to take couple of minutes. Please use
couple? 2-3 ... 5 -10? Can we timebox?

2018-07-26 21:45 UTC, CuriousVini commented on cdap-docs/reference-manual/source/http-restful-api/metadata.rst
> +will not have all the metadata. Metadata migration is expected to take couple of minutes. Please use
We have not specified any number here because the time would depend on how much data needs migration. However, we do not expect it to be too long.

2018-07-26 21:53 UTC, CuriousVini commented on cdap-docs/reference-manual/source/http-restful-api/metadata.rst
> +will not have all the metadata. Metadata migration is expected to take couple of minutes. Please use
Actually I think 2-3 minutes is a good number.

2018-07-26 21:54 UTC, CuriousVini commented
Thanks @deb-saunders For the quick review, I have addressed the comments in a separate commit. Please take a look at it when you get a chance, thanks!

2018-07-27 01:31 UTC, sreevatsanraman approved these changes

2018-07-27 03:09 UTC, merged