Ticket #285 | Variable Substitution Depth issue
cdapio/cdap pull request #10751
Opened 2018-10-01 17:07 UTC by chawlaasumit

2018-10-01 17:13 UTC, chtyim commented
What is the JIRA number for this?

2018-10-01 17:16 UTC, chtyim requested changes

2018-10-01 17:16 UTC, chtyim commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextConfig.java
> +    cConf.set(HCONF_ATTR_PLUGINS, GSON.toJson(plugins, PLUGIN_MAP_TYPE));
Why need to store in both cConf and hConf?

2018-10-01 17:16 UTC, chtyim commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextConfig.java
> +    cConf.set(HCONF_ATTR_PLUGINS, GSON.toJson(plugins, PLUGIN_MAP_TYPE));
The right fix should be not doing variable substitution when getting the plugin attributes from the configuration.

2018-10-02 17:20 UTC, chawlaasumit commented
creating fresh pull request

2018-10-02 17:20 UTC, closed without merging