CDAP-14462 add docs for cdap env
cdapio/cdap pull request #10774
Opened 2018-10-04 00:55 UTC by yaojiefeng

This pr depends on #10772

2018-10-04 20:43 UTC, dereklwood requested changes
some minor rewordings.

Maybe not for this PR, but I also think there should be a "Configuring Sandbox" section above this (prior to start/stop), where this should go.

2018-10-04 20:43 UTC, dereklwood commented on cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
> +Customize JVM OPTS For Sandbox on Linux
lower case `for` (or maybe just remove "For Sandbox on Linux")

2018-10-04 20:43 UTC, dereklwood commented on cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
> +On Linux, you can customize the jvm options for OutOfMemory error and whether to do a heapdump if an OutOfMemory error
capitalize `JVM`

2018-10-04 20:43 UTC, dereklwood commented on cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
> +happens. By default, CDAP process will be force killed if an OutOfMemory error happens and there will be no heapdump.
s/happens/occurs/g (2 times)

2018-10-04 20:43 UTC, dereklwood commented on cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
> +happens. By default, CDAP process will be force killed if an OutOfMemory error happens and there will be no heapdump.
"By default, if an OutOfMemory error occurs, the CDAP Sandbox will be killed and no heap dump will be performed"

2018-10-04 20:43 UTC, dereklwood commented on cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
> +You can configure these settings by editing the ``cdap-env.sh`` file under your ``conf`` directory. To change
"To customize these settings, edit the ``cdap-env.sh`` file under the `./conf` directory" (./ added for consistency with `./bin` directory above)

2018-10-04 20:43 UTC, dereklwood commented on cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
> +the behavior, change the value of ``KILL_ON_OOM_OPTS`` in ``cdap-env.sh``. To enable the heapdump, uncomment the line of
"To enable the heap dump, ensure ``HEAPDUMP_ON_OOM`` is set to ``true`` in ``cdap-env.sh``" . (this is just to make the docs more resilient if we ever change that line in cdap-env.sh)

2018-10-04 21:03 UTC, yaojiefeng commented
Thanks for the review! I have opened https://issues.cask.co/browse/CDAP-14464 as an improvement to talk about the configuration we can do for sandbox.

2018-10-05 00:29 UTC, dereklwood requested changes
one more minor inconsistency, otherwise lgtm

2018-10-05 00:29 UTC, dereklwood commented on cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
> +On Linux, you can customize the JVM options for OutOfMemory error and whether to do a heapdump if an OutOfMemory error
`heapdump` here vs `heap dump` elsewhere.  I *think* it's supposed to be `heap dump`

2018-10-05 17:11 UTC, dereklwood approved these changes

2018-10-05 18:51 UTC, merged