[UI][Theme] Add flag to make "About CDAP" modal configurable.
cdapio/cdap pull request #10770
Opened 2018-10-03 20:41 UTC by ajainarayanan

- Adds a feature flag to show/hide About CDAP modal in UI
- Updates theme files to have the newly added flag with default value.
- Fixes the Hub button to have proper margins in different sections of the UI (Admin -> Configuration for instance)

Build: https://builds.cask.co/browse/CDAP-URUT143

2018-10-04 02:54 UTC, elfenheart reviewed
one minor comment

2018-10-04 02:54 UTC, elfenheart commented on cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
> +            <If condition={Theme.showAboutProductModal}>
nit: we are being explicit in other places `Theme.showAboutProductModal === true`

2018-10-04 14:02 UTC, nitinmotgi commented on cdap-ui/server/config/themes/light.json
> +    "about-product-modal": true,
Can we just use about-product please

2018-10-04 14:02 UTC, nitinmotgi requested changes
Minor change

2018-10-04 22:44 UTC, elfenheart approved these changes
👍 LGTM

2018-10-05 03:50 UTC, ajainarayanan commented
Latest green build: https://builds.cask.co/browse/CDAP-URUT143-4

2018-10-05 03:51 UTC, nitinmotgi commented
LGTM 👍

2018-10-05 03:53 UTC, nitinmotgi approved these changes

2018-10-05 03:53 UTC, merged