Added tests for co.cask.cdap.api.common.Bytes
cdapio/cdap pull request #11196
Opened 2019-03-14 12:05 UTC by freddytuxworth

### What is this PR for?
I analysed this codebase and found that the `Bytes` class could do with some more unit tests. I have written a few tests for this class with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/datasheet). Hopefully these tests will help you to detect any regressions caused by future code changes.

Please let me know if there are any other areas of this project which you'd like tests written for - I'd be more than happy to help.

2019-03-14 12:16 UTC, chtyim requested changes
Please follow the coding style of existing code. We use 2 spaces for indention and all local variables are camelCase, started with lower case.

Please refer to 
https://wiki.cask.co/display/CE/Contributing+to+CDAP
and
https://wiki.cask.co/display/CE/Coding+Standard
for more information

2019-03-14 12:18 UTC, chtyim commented on cdap-api/src/test/java/co/cask/cdap/api/common/BytesTest.java
> +        Assert.assertEquals(4, Bytes.compareTo(a, empty));
The contract of `compareTo` is to return '< 0', '0' or '> 0'. Please test on the contract instead of the exact value returned.

2019-03-14 12:26 UTC, nitinmotgi commented
We would appreciate if you could either sign ICLA https://cla.developers.google.com/about/google-individual or CCLA https://cla.developers.google.com/about/google-corporate

This is only done the first time, after that we will be able to merge your approved PRs. 

Thanks again for your contributions.

2019-03-14 14:40 UTC, freddytuxworth commented
I have made the requested changes, is there anything else?

2019-03-20 05:29 UTC, nitinmotgi commented
Have you signed xCLA ?

2019-03-20 11:41 UTC, freddytuxworth commented
@nitinmotgi yes

2019-03-20 16:26 UTC, nitinmotgi approved these changes
+1

2019-03-20 16:42 UTC, chtyim commented
Build running in https://builds.cask.co/browse/CDAP-DUT6931

2019-03-20 16:42 UTC, chtyim approved these changes

2019-03-20 17:06 UTC, anew requested changes
The Bytes class was originally taken from the HBase code base. I guess at that time the tests should have been copied, too. I think if we add tests for Bytes now, it would make sense to incorporate the original tests from HBase: https://github.com/apache/hbase/blob/master/hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestBytes.java, and add more tests for the methods that Cask added after cloning the code. What do you think?

2019-03-28 10:18 UTC, anew approved these changes
we can also add the original HBase tests in a follow-up PR

2019-03-28 17:56 UTC, merged