Adding extra detailed debugging logs
cdapio/cdap pull request #14026
Opened 2022-02-14 08:03 UTC by sahusanket

2022-02-14 08:08 UTC, janakigg approved these changes

2022-02-14 16:33 UTC, sahusanket commented
original pr : https://github.com/cdapio/cdap/pull/13755

2022-02-14 23:03 UTC, tivv requested changes

2022-02-14 23:03 UTC, tivv commented on cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
> +    Bucket bucketObj = getStorageClient().get(bucket);
bucketObj can be null

2022-02-15 15:59 UTC, tivv approved these changes

2022-02-15 17:44 UTC, merged