Added Windows Aggregation Definition in CDAP
cdapio/cdap pull request #14501
Opened 2022-08-29 19:17 UTC by udurbha

As part of Bigquery Pushdown, where instead spark sql function calls ,bigquery function calls are executed,added windows aggregation definition.Followed by Bigquery Windows aggregation function calls implementation in google-cloud repo and transform method will be in WIndows-aggregation repo.

2022-09-28 20:07 UTC, fernst commented on cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/WindowsAggregationDefinition.java
> +        public FilterFunction getFilterFunction() {
Spacing is off here.

2022-09-28 20:08 UTC, fernst commented on cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/WindowsAggregationDefinition.java
> +            windowsExpressions = Collections.emptyList();
I don't think these are mutable instances. You need to initialize them using new ArrayList() and new HashMap();

2022-09-28 20:08 UTC, fernst commented on cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
> +  PUSHDOWN_TRANSFORMATION_WINDOWSAGGREGATION("6.8.0"),
this would be for 6.9.0

2022-09-28 20:10 UTC, fernst requested changes
Added a few comments/suggestions.

2022-09-29 14:36 UTC, closed without merging

2022-09-29 14:36 UTC, udurbha commented
PR was sent before Design Doc.