[CDAP-7264] create apps with version
cdapio/cdap pull request #6750
Opened 2016-09-16 19:37 UTC by maochf

2016-09-16 19:38 UTC, anwar6953 commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    LOG.info("@PUT @Path:/apps/{app-id} reached");
remove?

2016-09-16 19:38 UTC, maochf commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    LOG.info("@PUT @Path:/apps/{app-id} reached");
Still need it to debug, will remove later

2016-09-16 19:39 UTC, anwar6953 commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    LOG.info("@GET @Path:/apps/{app-id} reached");
remove?

2016-09-16 19:39 UTC, anwar6953 commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +      responder.sendString(HttpResponseStatus.INTERNAL_SERVER_ERROR, "Deploy failed: {}" + ex.getMessage());
`{}` is not doing anything here.

2016-09-16 19:39 UTC, anwar6953 commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +      throw new BadRequestException(String.format("Path parameter namespace-id cannot be empty"));
no need for String.format here

2016-09-16 19:41 UTC, anwar6953 commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +    HttpEntityEnclosingRequestBase request;
no need to declare and initialize on separate lines

2016-09-16 19:44 UTC, sreevatsanraman commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +  @Path("/apps/new/{app-id}/versions/{version-id}/create")
We should review the APIs. Should not have new in the path. #

2016-09-16 19:45 UTC, sreevatsanraman commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    LOG.info("@GET @Path:/apps/{app-id}/versions/{version-id} reached");
Remove all the log lines

2016-09-16 19:46 UTC, maochf commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +  @Path("/apps/new/{app-id}/versions/{version-id}/create")
yes, this is just a temporary fix in order to run the test and validate the changes for it

2016-09-16 19:47 UTC, chtyim commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    if (appId == null) {
This is duplicated as in the `validateApplicationId` method. Why not just call that method?

2016-09-16 19:48 UTC, chtyim commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    LOG.info("@GET @Path:/apps/{app-id}/versions/{version-id} reached");
Don't log info for rest endpoint. It will pollute the logs.

2016-09-16 19:50 UTC, sreevatsanraman commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +  public void testDeployVersionedApp() throws Exception {
We should add tests for - get versioned app, getting app without versions, deleting

2016-09-16 19:51 UTC, sreevatsanraman requested changes
- Needs REST API review
- Needs more test cases.
- Removing Log Lines

2016-09-16 19:56 UTC, maochf commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    if (appId == null) {
That method directly returns an ApplicationId with a default version.  I've also been thinking merging them. How about calling `validateApplicationVersionId (namespaceId, appId, DEFAULT_VERSION)` from `validateApplicationId`?

2016-09-16 20:02 UTC, maochf commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +  public void testDeployVersionedApp() throws Exception {
Will do

2016-09-16 22:12 UTC, maochf commented
http://builds.cask.co/browse/CDAP-RUT172-1 build is green

2016-09-17 21:10 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +//    Assert.assertEquals(200,
Does this need to be un-commented?

2016-09-18 07:01 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +      responder.sendString(HttpResponseStatus.INTERNAL_SERVER_ERROR, "There already exists application version " +
This is not an internal server error since user is trying to add multiple version of the same app. I think conflict would be better.

2016-09-18 07:01 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +        "with no '-SNAPSHOT' suffix for the same application to be deployed");
Let's not expose '`-SNAPSHOT` in the error message (since it is an implementation detail)

2016-09-18 07:03 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +  protected HttpResponse getNonVersionedAppResponse(String namespace, String appName)
It would be a good idea to call this method from getAppDetails() method above

2016-09-18 07:04 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +  protected HttpResponse getVersionedAppResponse(String namespace, String appName, String appVersion) throws Exception {
It would be a good idea to call this method from getAppDetails() method below

2016-09-18 07:09 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +    Id.Application appIdDefault = Id.Application.from(Id.Namespace.DEFAULT, appId.getApplication());
It would be a good idea to add some comments on what the test is doing. For example over here you can say `// Deploy non-versioned app`

2016-09-18 07:10 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +    ApplicationId appIdV2 = new ApplicationId(appId.getNamespace(), appId.getApplication(), "version_2");
Over here you can say `// Deploy app with version_2`

2016-09-18 07:13 UTC, poornachandra reviewed
@maochf Few more comments to address. Also file a JIRA for `updating of a version (say v1) of an app is allowed as long as v1 has the suffix of ‘-SNAPSHOT'`

2016-09-18 08:25 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +        "existing version(s)");
Let's change this to `Cannot update the application because version versionId already exists`

2016-09-18 08:29 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +   * TODO: Delete an application specified by appId and versionId.
This TODO needs to be addressed

2016-09-18 08:31 UTC, gokulavasan commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    if (EntityId.isValidId(versionId)) {
@poornachandra Is it ok to place a restriction that version-id needs to be a valid CDAP Id?

2016-09-18 08:33 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
> +    return version.endsWith("-SNAPSHOT");
Use `DEFAULT_VERSION` constant here

2016-09-18 08:37 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +  protected HttpResponse deploy(ApplicationId appId,
Since this method and the above method have the same functionality, one can call another, right? This will reduce code duplication.

2016-09-18 08:40 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +    ApplicationId appId = new ApplicationId(Id.Namespace.DEFAULT.getId(), "cfgAppWithVersion", "version_1");
We should allow versions such as `1.0.0`, etc. I think I saw that we enforce versionId to be an entity id above. Is that check required for version id @gokulavasan ?

2016-09-18 08:46 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +    // Update app with default versionId by versioned API
I don't see any difference between versioned API and non-versioned API in this test case. Do we need to call them out separately?

2016-09-18 08:47 UTC, poornachandra reviewed
@maochf Good progress, few more minor comments to address

2016-09-18 08:48 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +    if (EntityId.isValidId(versionId)) {
I have the same question in my comments below. I think we should allow versions like `1.0.01`, etc. Let's remove this check.

2016-09-18 08:49 UTC, poornachandra commented
Also let's file a JIRA for using the artifact version as the app version when version is not specified during app deployment.

2016-09-18 08:52 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +    ApplicationId appId = new ApplicationId(Id.Namespace.DEFAULT.getId(), "cfgAppWithVersion", "version_1");
Also change `version_1` here to `1.0.0` once this change is made.

2016-09-18 08:53 UTC, maochf commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +        "existing version(s)");
Will this be confusing for the user since they can update the application sometimes when the versionId ends with "-SNAPSHOT"?

2016-09-18 08:59 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +        "existing version(s)");
We will document this behavior. Also we already have that behavior with artifacts, so users should be used to this by now.

2016-09-18 09:09 UTC, maochf commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +    // Update app with default versionId by versioned API
The non-versioned test case uses ` deploy(appIdDefault, requestDefault)` which calls the original POST API without version, while the versioned API test case uses`deploy(appIdDefault.toEntityId(), requestDefault2)`  which will call versioned POST API by explicitly setting the version as default versionId

2016-09-18 09:17 UTC, maochf commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +  protected HttpResponse deploy(ApplicationId appId,
They have different deployPath and request method. I extract their common codes into a function.

2016-09-18 09:18 UTC, maochf commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +   * TODO: Delete an application specified by appId and versionId.
How about finishing it in another PR?

2016-09-18 09:26 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +   * TODO: Delete an application specified by appId and versionId.
+1

2016-09-18 09:26 UTC, poornachandra commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
> +    // Update app with default versionId by versioned API
I see, if the code is different then it is fine

2016-09-18 09:38 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
> +        " versionId already exists");
versionId here should be the variable `versionId`

2016-09-18 09:40 UTC, poornachandra reviewed
@maochf One last comment to fix and this PR is good to merge. Please squash commits and merge after build is green.

2016-09-18 18:35 UTC, maochf commented
PR created for the TODO delete API: https://issues.cask.co/browse/CDAP-7296

2016-09-18 21:32 UTC, maochf commented
Build is green, ready to merge

2016-09-18 21:34 UTC, merged