[CDAP-7275] Feature/ui cask market detail
cdapio/cdap pull request #6754
Opened 2016-09-16 22:34 UTC by elfenheart

branched of: https://github.com/caskdata/cdap/pull/6745

JIRA: https://issues.cask.co/browse/CDAP-7275

2016-09-16 22:39 UTC, nitinmotgi commented on cdap-ui/app/cdap/components/CaskMarketPlace/index.js
> +export default class CaskMarketPlace extends Component {
```CaskMarket``` instead of ```CaskMarketPlace```

2016-09-16 22:40 UTC, nitinmotgi commented on cdap-ui/app/cdap/api/caskmarket/index.js
> +const basepath = 'http://marketplace.cask.co.s3.amazonaws.com';
Please take it from the configuration.

2016-09-16 22:42 UTC, nitinmotgi reviewed
`CaskMarketPlace` should be `CaskMarket` or just `Market`.  Let's remove Cask from the code please.

2016-09-16 22:43 UTC, nitinmotgi requested changes
Please address the suggested changes. Thanks.

2016-09-19 22:10 UTC, elfenheart commented on cdap-ui/app/cdap/api/caskmarket/index.js
> +const basepath = 'http://marketplace.cask.co.s3.amazonaws.com';
@nitinmotgi This ideally will come from cdap-site.xml. Will work with the backend people to add it to cdap-site.xml. 

Opened JIRA: https://issues.cask.co/browse/CDAP-7303

2016-09-19 22:34 UTC, ajainarayanan commented
👍 LGTM

2016-09-19 22:36 UTC, merged