Feature/ui wizard create stream
cdapio/cdap pull request #6759
Opened 2016-09-19 08:02 UTC by ajainarayanan

- Adds following components,
  - `Wizard` - A wrapper that connects everything that we call as wizard
  - `WizardModal` - A wrapper for dropping in the modal anywhere we want. A generic re-usualble way to show modal(wizards) anywhere in a more consistent way.
  - `ResourceCenter` - Nothing fancy as of now. Just shows a dummy list of entities that we can create in CDAP
  - `ResourceCenter Entity` - A short info on the entity that is being created + a create link (to be used in the resource center)
  - `TimeToLive` - A naive implentation of setting ttl for streams in UI (Need some inputs)
  - `SelectWithOptions` - One element to render a dropdown instead of nesting `<Input>` with `<options>` like the one from reactstrap. This is specifically useful when we use `connect` from `react-redux`
  - `SimpleSchema` - A naive implementation of a simple schema editor. Nothing fancy. A table of textbox, dropdown, checkbox & a delete button (just like the way we have in hydrator).

- Adds following services,
  - `WizardConfigs` - One place to find all WizardConfigurations that are being used in CDAP
  - `WizardStores` - Once place to find all stores used by each Wizard instances. 

- Have added aliases to webpack to refer to any component/service from anywhere in the application (could avoid using relative paths with a lot of `../.`)

- Have added an optional field in `ui-settings.json` to enable debugging in UI (console log in the browser).

#### Note:
- TTL is not yet integrated with backend.
- Haven't added the functionality of disabling steps after finishing creating a stream
- Working on i18n and will add as separate PR as this has already exceeded the limit we can review.
- Upload data coming soon.

2016-09-19 21:55 UTC, elfenheart commented on cdap-ui/app/cdap/components/CaskWizards/StreamCreate/SchemaStep.js
> +  console.log('asdasd', CreateStreamStore);
remove

2016-09-19 22:04 UTC, elfenheart requested changes

2016-09-20 18:28 UTC, ajainarayanan commented
Closing the PR and opening the same against feature/cdap-4-sneak-peek

2016-09-20 18:40 UTC, elfenheart commented on cdap-ui/app/cdap/api/stream/index.js
> +let basepath = '/namespaces';
we can just change this basepath to ```/namespaces/:namespace/streams```

2016-09-21 05:53 UTC, elfenheart approved these changes

2016-09-21 05:53 UTC, elfenheart commented
👍  LGTM

2016-09-21 06:04 UTC, ajainarayanan commented
Have squashed the commits and hence merging.

2016-09-21 06:04 UTC, merged