Adds i18n for Wizard + add communication between wizard & actions from usecase
cdapio/cdap pull request #6764
Opened 2016-09-20 09:07 UTC by ajainarayanan

###Note:
This PR is branched off from #6759 
DO NOT MERGE THIS PR BEFORE THAT

- Adds i18n for Wizards.
- Adds `AbstractWizard` component to abstract consumers using wizard with just type of wizard and store specified for usage.
- Adds adhoc way of notifying the actions (whether its done or not) and updates UI for actions appropriately.

#### WIP:
- Styling
- Refining how wizards and actions interact with each other
- Upload data to streams in stream wizard
- Deploy a pipeline with just JSON and navigate to respective detailed view of pipeline in hydrator.

2016-09-20 18:28 UTC, ajainarayanan commented
Closing the PR and opening the same against `feature/cdap-4-sneak-peek`

2016-09-21 20:05 UTC, elfenheart commented on cdap-ui/app/cdap/components/CaskWizards/StreamCreate/UploadStep/index.js
> +              Select file to be uploaded to Stream
I18n?

2016-09-21 20:05 UTC, elfenheart commented on cdap-ui/app/cdap/components/CaskWizards/StreamCreate/index.js
> +              title={this.props.context ? this.props.context + " | Create Stream" : "Create Stream"}
i18n

2016-09-21 20:08 UTC, elfenheart commented on cdap-ui/app/cdap/components/Wizard/index.js
> +                      Step - {value.index} : {value.label} - {value.complete ? 'Done' : 'Skipped'}
I18n

2016-09-21 20:09 UTC, elfenheart commented on cdap-ui/app/cdap/text/text-en.yaml
> +      create_artifact: Create Artifact
We should order these alphabetically so it's easy to navigate

2016-09-21 20:09 UTC, elfenheart requested changes

2016-09-21 22:38 UTC, elfenheart commented on cdap-ui/app/cdap/components/Wizard/index.js
> +      return (
we should avoid assigning function to const 
ref: https://github.com/airbnb/javascript#functions

2016-09-22 02:40 UTC, ajainarayanan commented on cdap-ui/app/cdap/components/CaskWizards/StreamCreate/UploadStep/index.js
> +              Select file to be uploaded to Stream
Ignore this. This is getting removed in the next PR.

2016-09-22 02:41 UTC, ajainarayanan commented on cdap-ui/app/cdap/components/Wizard/index.js
> +      return (
Hhmm it doesn't say avoid using const. It says use named functions. Ok will do.

2016-09-22 21:40 UTC, elfenheart commented
👍  LGTM

2016-09-22 22:55 UTC, ajainarayanan commented
Will create a separate PR for update based on namespace changes. Merging this for now

2016-09-22 22:55 UTC, merged