use hbase 12 support and IBM version match updated to support IBM
cdapio/cdap pull request #6881
Opened 2016-10-04 21:35 UTC by gsps1

The HBase-CDAP-1.1 compat module is source compatible with 1.2, so we are using 1.1 compat for non-cdh hbase-1.2 versions. 

This also adds version match for IBM, where the version string is different with existing version match for HDP and CDH Hbase versions. Changes have been tested on IBM cluster successfully.

Also includes HBaseVersion tests.

2016-10-04 21:36 UTC, gsps1 commented
Build running : http://builds.cask.co/browse/CDAP-DUT4911-1

2016-10-04 21:43 UTC, wolf31o2 requested changes
A couple minor comments

2016-10-04 21:43 UTC, wolf31o2 commented on cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java
> +      Matcher ibmMatcer = IBM_PATTERN.matcher(versionString);
ibmMatc**h**er, please

2016-10-04 21:43 UTC, wolf31o2 commented on cdap-data-fabric/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java
> +          currentVersion = Version.HBASE_11;
Please put a comment here so we know that the 1.2 code is compatible with the 1.1 module

2016-10-04 21:47 UTC, wolf31o2 commented
Also, put CDAP-6937 in the commit message, please.

2016-10-05 20:07 UTC, gsps1 commented
thanks chris, addressed the comments.

2016-10-07 01:21 UTC, wolf31o2 approved these changes

2016-10-07 01:22 UTC, wolf31o2 commented
👍 LGTM

2016-10-07 01:26 UTC, merged