Feature/merge 3.6 develop
cdapio/cdap pull request #6894
Opened 2016-10-05 18:52 UTC by CuriousVini

Conflicts: 

- Hash in build.sh
- version in json
- AuthServerAnnounceTest#startUp() was creating object of NettyRouter. Changed it to use cConf as well.

Build passes locally.

2016-10-05 18:57 UTC, wolf31o2 commented on cdap-ui/server/config/cdap-ui-config.json
> +      "version": "0.2.0",
This shouldn't be changed on `develop`

2016-10-05 18:58 UTC, wolf31o2 commented on cdap-examples/SparkPageRank/pom.xml
> +>>>>>>> release/3.6
Conflict which needs resolving.

2016-10-05 19:00 UTC, wolf31o2 commented on cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json
> +                        "version": "1.4.1"
Keep the version from `develop` not `release/3.6`

2016-10-05 19:04 UTC, wolf31o2 commented on cdap-ui/templates/apps/predefined/AmazonSQSToHBase.json
> +                        "version": "1.4.1"
Keep the version from `develop` not `release/3.6`

2016-10-05 19:05 UTC, wolf31o2 commented on cdap-ui/templates/apps/predefined/EventClassifier.json
> +                        "version": "1.4.1",
Keep the version from `develop` not `release/3.6`

2016-10-05 19:05 UTC, wolf31o2 commented on cdap-ui/templates/apps/predefined/EventClassifier.json
> +                        "version": "1.4.1",
Keep the version from `develop` not `release/3.6`

2016-10-05 19:05 UTC, wolf31o2 commented on cdap-ui/templates/apps/predefined/KafkaToHBase.json
> +                        "version": "1.4.1"
Keep the version from `develop` not `release/3.6`

2016-10-05 19:06 UTC, wolf31o2 requested changes
All of the JSON files need to keep the version from `develop` not `release/3.6`

2016-10-05 19:30 UTC, CuriousVini commented
@wolf31o2 Addressed comments. Built app-templates and cdap locally

2016-10-05 19:46 UTC, wolf31o2 approved these changes
JSON changes and `cdap-examples/SparkPageRank/pom.xml` look good. Were there other conflicts?

2016-10-05 19:47 UTC, CuriousVini commented
@wolf31o2 Hash changes in build.sh and AuthServerAnnounceTest#startUp() was creating object of NettyRouter. Changed it to use cConf as well.

2016-10-05 20:00 UTC, wolf31o2 commented
👍 LGTM

2016-10-06 01:35 UTC, CuriousVini commented
build is green. merging.

2016-10-06 01:35 UTC, merged