Add note about supporting other OSes.
cdapio/cdap pull request #6896
Opened 2016-10-05 18:59 UTC by awholegunch

2016-10-05 19:09 UTC, wolf31o2 requested changes
Maybe it would be better to mention that these are the lower bound on supported versions.

We support CentOS 6.0+ or Ubuntu 12.04+

2016-10-05 19:09 UTC, wolf31o2 commented on cdap-docs/admin-manual/source/_includes/installation/installation.txt
> +currently provide, they contain no OS-specific code, and the same packages will work on
They do contain OS-specific code, even distribution-specific code. However, they do not contain distribution **version** specific code.

2016-10-05 19:49 UTC, dereklwood commented
👍 lgtm

2016-10-06 17:44 UTC, wolf31o2 approved these changes
👍 LGTM

2016-10-06 18:20 UTC, merged