Feature/ui namespace wizard complete
cdapio/cdap pull request #6958
Opened 2016-10-17 22:39 UTC by PGuimarais

- Enables user to create namespace and apply settings / preferences in wizard
- Adds KeyValuePairs component 
- Adds Redux store for KeyValuePairs

2016-10-17 22:53 UTC, elfenheart requested changes

2016-10-17 22:53 UTC, elfenheart commented on cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePairs.less
> +}
Nest all these inside a parent container, these changes are applied globally for the same class name

2016-10-17 22:53 UTC, elfenheart commented on cdap-ui/app/cdap/components/KeyValuePairs/index.js
> +            <Provider store={this.keyValueStore} key={shortid.generate()}>
don't use shortid.generate here. Should be defined wherever the state.pairs being constructed

2016-10-17 23:42 UTC, elfenheart requested changes

2016-10-17 23:42 UTC, elfenheart commented on cdap-ui/app/cdap/services/WizardStores/AddNamespace/ActionCreator.js
> +    putParams["config"]["keytabURI"] = state.security.keytabURI;
check the proper state name of this keytab state

2016-10-17 23:43 UTC, elfenheart commented
![screen shot 2016-10-17 at 4 42 28 pm](https://cloud.githubusercontent.com/assets/4398643/19459566/c785eac2-9488-11e6-93ac-c41cf95aef3a.png)

2016-10-18 00:13 UTC, PGuimarais commented on cdap-ui/app/cdap/components/KeyValuePairs/index.js
> +            <Provider store={this.keyValueStore} key={shortid.generate()}>
moved the unique id to the redux store for each pair

2016-10-18 00:13 UTC, PGuimarais commented on cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePairs.less
> +}
done

2016-10-18 01:12 UTC, elfenheart commented
The error name Failed to features.Wizard.undefined.headerlabel still happening

2016-10-18 01:37 UTC, elfenheart commented
the preference store don't get reset i believe.

To reproduce:
1. Create a namespace, add preference
2. Create another namespace, go to the preference step, and the previous values will still be there

2016-10-24 20:45 UTC, ajainarayanan commented
👍 LGTM

2016-10-24 20:46 UTC, merged