Minor fix to documentation build
cdapio/cdap pull request #7183
Opened 2016-11-24 01:24 UTC by awholegunch

2016-11-24 01:28 UTC, chtyim commented
LGTM

2016-11-24 01:41 UTC, awholegunch commented
"On-hold": Found another bug.

2016-11-29 16:54 UTC, wolf31o2 requested changes
Couple minor comments

2016-11-29 16:54 UTC, wolf31o2 commented on cdap-docs/build.sh
> +  if [[ ${type} == "docs_set" ]] || [[ ${type} == "docs_web_only" ]]; then
This exact same conditional appears a couple lines below. Can these not be reordered and `clean_targets` put inside the below conditional?

2016-11-29 16:54 UTC, wolf31o2 commented on cdap-docs/reference-manual/build.sh
> +    fi
Useless. If you use `-f` on `rm` it will always exit 0.

2016-11-29 17:59 UTC, awholegunch commented on cdap-docs/build.sh
> +  if [[ ${type} == "docs_set" ]] || [[ ${type} == "docs_web_only" ]]; then
I think it can.

2016-11-29 19:19 UTC, awholegunch commented on cdap-docs/reference-manual/build.sh
> +    fi
Fixed.

2016-11-29 19:42 UTC, wolf31o2 approved these changes

2016-11-29 19:42 UTC, wolf31o2 commented
👍 LGTM

2016-11-29 19:43 UTC, merged