[TRACKER-247]  Data Dictionary Frontend Implementation
cdapio/cdap pull request #7321
Opened 2016-12-12 15:07 UTC by sushiladokar

https://issues.cask.co/browse/TRACKER-247

2016-12-12 18:17 UTC, russorat commented
General style comments: 1. Newlines at the end of each file. 2. functions should not have a space between the name and ().

2016-12-12 19:15 UTC, anwar6953 commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +    this.piTitle = 'PII data is any information that is sensitive and should be handled with extro care and security.';
extro --> extra

2016-12-12 21:14 UTC, sreevatsanraman commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +    this.piTitle = 'PII data is any information that is sensitive and should be handled with extro care and security.';
@elfenheart : should this text come from i18n?

2016-12-12 21:33 UTC, ajainarayanan commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +    this.piTitle = 'PII data is any information that is sensitive and should be handled with extro care and security.';
I don't think we have access i18n in angular apps. May be in 4.1.0? i18n anyways doesn't gets applied for hydrator and tracker today.

2016-12-12 22:18 UTC, awholegunch commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +    this.piTitle = 'PII data is any information that is sensitive and should be handled with extro care and security.';
should this be `this.piiTitle`? Should the phrase be:
```
this.piiTitle = 'PII (Personally Identifiable Information) is any information that is sensitive and needs to be handled with extra care and security.';

2016-12-13 05:37 UTC, elfenheart requested changes

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/templates/dictionary.html
> +                  <th width="10%">Actions
Table sizing should be done by CSS class instead of inline style

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/templates/dictionary.html
> +                  <script type="text/ng-template" id="display">
why is there a `<script>` here?

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +      dictionaryData: []
Is there any other property to `this.dictionary`? It doesn't seem like it, and if so, is there any specific reason why the dictionaryData array is within another object?

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +    }else{
codestyle: spaces after `}` and `else`

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +    this.addNewColumn=false;
space between `=`

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/controllers/dictionary-ctrl.js
> +      console.log('Error', err);
indentation

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/tracker.less
> +  main.container{
codestyle: space before `{`

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/tracker.less
> +    border-right: 0;
indentations

2016-12-13 05:37 UTC, elfenheart commented on cdap-ui/app/tracker/tracker.less
> +      color: #ccc;
didn't this break the stylelint? color should be 6 characters `#cccccc'

2016-12-13 19:04 UTC, ajainarayanan commented on cdap-ui/app/tracker/templates/partial/dictionary-row-display.html
> +<td class="column-cell"><span>{{((DictionaryController.currentPreferredPage-1)*10)+$index+1}}</span>{{ data.columnName }}</td>
This file is missing license header.

2016-12-13 19:05 UTC, ajainarayanan commented on cdap-ui/app/tracker/templates/partial/dictionary-row-edit.html
> +<td><span>{{$index+1}}</span>{{ data.columnName }}</td>
Same here too. This will break the maven build.

2016-12-14 06:04 UTC, elfenheart commented on cdap-ui/app/tracker/templates/dictionary.html
> +    <div ng-if="DictionaryController.dictionaryData.length > 0"
What happens when the length is 0? Currently we don't really show anything

2016-12-14 06:12 UTC, elfenheart commented on cdap-ui/app/tracker/templates/dictionary.html
> +    <div ng-if="DictionaryController.dictionaryData.length > 0"
It might be good to initialize with an empty row, so the user know they can input something

2016-12-14 19:30 UTC, elfenheart approved these changes

2016-12-15 04:20 UTC, elfenheart commented
When there is an error in saving a row, no error message is being shown. It's confusing to the user what is happening.

2016-12-15 06:31 UTC, sushiladokar commented on cdap-ui/app/tracker/templates/partial/dictionary-row-display.html
> +<td class="column-cell"><span>{{((DictionaryController.currentPreferredPage-1)*10)+$index+1}}</span>{{ data.columnName }}</td>
Added the license header

2016-12-15 06:31 UTC, sushiladokar commented on cdap-ui/app/tracker/templates/partial/dictionary-row-edit.html
> +<td><span>{{$index+1}}</span>{{ data.columnName }}</td>
Added the license header

2016-12-15 06:40 UTC, elfenheart commented
👍 LGTM. Please squash commits

2016-12-15 06:56 UTC, merged