CDAP-6595 Authorization for Metadata
cdapio/cdap pull request #7514
Opened 2017-01-03 20:11 UTC by rohitsinha54

Opened PR https://github.com/caskdata/cdap/pull/7304 against develop. The PR was already reviewed there. 

Issue: https://issues.cask.co/browse/CDAP-6595

- Added authorization for Metadata (Tags and Properties)

2017-01-13 19:56 UTC, Nishith requested changes

2017-01-13 19:56 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
>    void removeMetadata(NamespacedEntityId namespacedEntityId) throws NotFoundException;
Shouldn't this and the three after this throw the UnauthorizedException?

2017-01-13 19:56 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
> +    throws Exception {
What else does this throw, other than the three that the one's before it are throwing?

2017-01-13 19:56 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
> +                             @QueryParam("scope") String scope) throws Exception {
Is this now throwing any additional exception other than UnauthorizedException?

2017-01-26 23:16 UTC, rohitsinha54 commented
On hold to focus on higher priority tasks of 4.1

2017-02-08 00:47 UTC, closed without merging