CDAP-7683 add a tool to upload coprocessor jars
cdapio/cdap pull request #7676
Opened 2017-01-25 01:02 UTC by albertshau

Added a tool that will build and upload coprocessor jars to HDFS.
The tool will run before the master starts, and can also be
run on its own. It can be used on a slave cluster to ensure that
required coprocessor jars are on HDFS even though CDAP is not
running on the cluster.

Refactored the logic around building coprocessors so that
HBaseTableAdmin and HBaseQueueAdmin no longer build their required
coprocessor on demand, but just assume the coprocessor exists at
a pre-defined location. Logic for building the actual jar was
just moved from HBaseTableUtil to a new CoprocessorManager class.

2017-01-25 01:02 UTC, albertshau commented
http://builds.cask.co/browse/CDAP-DUT5318

2017-01-25 02:01 UTC, sagarkapare reviewed
Minor nits. Rest LGTM 👍

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +  protected final Location jarDir;
nit: `private`

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +   * In distributed mode, the coprocessor jars are loaded onto hdfs by the CoprocessBuildTool,
nit: `CoprocessorBuildTool`

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +    LOG.debug("Creating jar file for coprocessor classes: " + buf.toString());
nit: use `{}` syntax with LOG.

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +    final byte[] buffer = new byte[4 * 1024];
better to move above two declarations close to where they are used. i.e. below the following for loop

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +   * @throws IllegalStateException if the coprocessor jar does not exist
where are we throwing `IllegalStateException`?

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +      return null;
method should be marked `@Nullable`

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +    LOG.debug("Adding " + dependentClasses.size() + " classes to jar");
nit: use `{}` syntax

2017-01-25 02:01 UTC, sagarkapare commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtil.java
>  import com.google.common.hash.Hasher;
unused import?

2017-01-25 02:04 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
can this not just call the new ``cdap_setup_tool`` function to do the same thing?

2017-01-25 02:06 UTC, albertshau commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
the problem is it would re-run all the functions that set classpath and everything.

2017-01-25 02:07 UTC, albertshau commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/HBaseTableUtil.java
>  import com.google.common.hash.Hasher;
it was only used in the method to create the coprocessor jar, which got moved

2017-01-25 02:07 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
Also note that if this is desirable in a CM environment, a corresponding update is needed to the CSD control.sh script (it does not use ``cdap_start_java``)

2017-01-25 02:08 UTC, albertshau commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +   * @throws IllegalStateException if the coprocessor jar does not exist
sorry, was originally there but removed it. will remove this line.

2017-01-25 02:10 UTC, albertshau commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +      return null;
this should never happen anymore, will remove it.

2017-01-25 02:13 UTC, albertshau commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> +    final byte[] buffer = new byte[4 * 1024];
the hasher isn't actually used anymore either, I'll remove it.

2017-01-25 02:26 UTC, albertshau commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
Is that script in this repo? Can't seem to find it.

2017-01-25 02:29 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
no, sorry, separate repo:  https://github.com/caskdata/cm_csd/blob/develop/src/scripts/cdap-control.sh

2017-01-25 18:20 UTC, wolf31o2 requested changes
Couple changes

2017-01-25 18:20 UTC, wolf31o2 commented on cdap-common/bin/cdap
> +  setup) shift; cdap_setup_tool ${@}; __ret=${?} ;;
This name is really ambiguous, especially given this is a very specific use case. Maybe `hbase_setup` or something, instead? This makes it seem like it's used for more than just adding coprocessors to HBase.

2017-01-25 18:20 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
Those functions *should* be no-op/idempotent, if the variables are already set. If they're not, it's a bug. It's better to setup the function in a way that we reuse it, versus having the same code in multiple places.

2017-01-25 18:20 UTC, wolf31o2 commented on cdap-common/bin/cdap
> +    echo "    setup        - Ensures CDAP coprocessors are present on HDFS"
HBase coprocessors

2017-01-25 18:20 UTC, wolf31o2 commented on cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/CoprocessorManager.java
> + * Copyright © 2016 Cask Data, Inc.
2017

2017-01-25 18:20 UTC, wolf31o2 commented on cdap-master/src/main/java/co/cask/cdap/data/tools/CoprocessorBuildTool.java
> + * Copyright © 2016 Cask Data, Inc.
2017

2017-01-25 19:00 UTC, albertshau commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
ok cool i'll try that then

2017-01-25 22:18 UTC, albertshau commented on cdap-common/bin/functions.sh
> +    "${JAVA}" ${JAVA_HEAPMAX} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.data.tools.CoprocessorBuildTool </dev/null >>${__logfile} 2>&1
i'll open a jira for the CM work

2017-01-25 22:30 UTC, wolf31o2 requested changes
One kinda major change... this code is fine, as is... but I think we should make the change now to fit with what's been approved before.

2017-01-25 22:30 UTC, wolf31o2 commented on cdap-common/bin/cdap
> +  setup) shift; cdap_hbase_setup ${@}; __ret=${?} ;;
I was thinking of the argument being more `hbase_setup` than the function name. Sorry that I wasn't clear.

However, this isn't something that Nitin likes. You can see on the [wiki](https://wiki.cask.co/display/CE/CDAP+Scripts) that we're using compound commands, versus underscored ones. This was something that he specifically had me change in the other implementations, so I think we'll need to apply that here, too.

Maybe this should be `cdap setup hbase`?

```bash
  setup) shift; cdap_setup ${@}; __ret=${?} ;;
```
Then, the `cdap_setup` function would be something like:
```bash
cdap_setup() {
  local __action=${1}
  shift
  cdap_setup_${__action} ${@}
  return $?
}
```

2017-01-25 22:30 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +# cdap_hbase_setup [arguments]
If using ideas from above: `cdap_setup_hbase`

2017-01-25 22:30 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +  logecho "$(date) Ensuring required HBase coprocessors are on HDFS"
Move this up to where we're calling `cdap_hbase_setup` in `cdap_start_java` so we don't write to the log when called on the command line.

2017-01-25 23:17 UTC, albertshau commented on cdap-common/bin/cdap
> +  setup) shift; cdap_hbase_setup ${@}; __ret=${?} ;;
ah ok got it

2017-01-26 00:50 UTC, wolf31o2 approved these changes

2017-01-26 03:28 UTC, merged