CDAP-4931: Use Path instead of URIs for Artifacts
cdapio/cdap pull request #7692
Opened 2017-01-26 17:12 UTC by deepakwadhwani

Includes fix for Unit Tests. 
Clean Build: http://builds.cask.co/browse/CDAP-DUT5328-1

2017-01-26 17:38 UTC, albertshau requested changes

2017-01-26 17:38 UTC, albertshau commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
> +        locationPath = locationURI.getPath();
doesn't this have the same problem as before where its not relative?

2017-01-26 17:38 UTC, albertshau commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
> +        artifactLocationPath = locationURI.getPath();
same here

2017-01-26 17:38 UTC, albertshau commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
> +        artifactLocationPath = locationURI.getPath();
and here

2017-01-26 23:53 UTC, deepakwadhwani commented
Build running: http://builds.cask.co/browse/CDAP-DUT5328-3

2017-01-27 00:03 UTC, albertshau commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
>      ArtifactData(Location location, ArtifactMeta meta) {
seems like we should only have this constructor

2017-01-27 00:03 UTC, albertshau commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
>      PluginData(PluginClass pluginClass, ArtifactRange usableBy, Location artifactLocation) {
seems like we should only have this constructor

2017-01-27 00:03 UTC, albertshau commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
>      AppData(ApplicationClass appClass, Location artifactLocation) {
seems like we should only have this constructor

2017-01-27 00:03 UTC, albertshau commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
> +      Location artifactLocation = this.artifactLocationURI != null
this logic is repeated 3 times and will be used in other places too. We can move it to the Locations class as something like `Locations.getCompatibleLocation(LocationFactory locationFactory, @Nullable String path, @Nullable URI uri)`

2017-01-27 01:12 UTC, albertshau approved these changes
lgtm

2017-01-27 16:35 UTC, deepakwadhwani commented
clean build: http://builds.cask.co/browse/CDAP-DUT5328

2017-01-27 23:57 UTC, merged