Making log partition key configurable
cdapio/cdap pull request #7766
Opened 2017-02-01 04:52 UTC by CuriousVini

Issue: https://issues.cask.co/browse/CDAP-8230
Build: http://builds.cask.co/browse/CDAP-DUT5374-1

Currently testing on cluster

2017-02-01 08:13 UTC, gsps1 requested changes
few comments

2017-02-01 08:13 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaLogAppender.java
> +      return loggingContext.getLogPartition();
its better if you construct the key explicitly than using the `getLogPartition`, as we might remove that if its no longer used after the refactor, also when looking at how key is constructed, its better for us to see it in this method.

2017-02-01 08:13 UTC, gsps1 commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
> +                                                              "RUN2", "INSTANCE2");
you are just publishing from one flow context ? you need to publish from two program context (from same app) to make sure they are reaching the same partition right ?

2017-02-01 08:13 UTC, gsps1 commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
> +    for (Map.Entry<Integer, Collection<String>> entry : actual.asMap().entrySet()) {
add some comments about what you are looking to test.

2017-02-01 18:06 UTC, CuriousVini commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaLogAppender.java
> +      return loggingContext.getLogPartition();
What do you mean explicitly? We do not get MDCPropertyMap at publisher side. Also I think when we remove LoggingContext#getLogPartition(), we should remove all the usages of it.

2017-02-01 18:14 UTC, CuriousVini commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
> +                                                              "RUN2", "INSTANCE2");
fixed

2017-02-01 18:28 UTC, CuriousVini commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
> +    for (Map.Entry<Integer, Collection<String>> entry : actual.asMap().entrySet()) {
done

2017-02-01 22:16 UTC, CuriousVini commented
@gsps1 Addressed comments and tested on cluster. Please take another look when you get a chance

2017-02-03 20:23 UTC, chtyim commented on cdap-common/src/main/resources/cdap-default.xml
> +    <name>log.publish.kafka.partition.key</name>
Can we not having the name `kafka` in the config? As the computation of the partition has nothing to do with Kafka.

2017-02-03 20:23 UTC, chtyim commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/LoggingConfiguration.java
> +  public static final String KAFKA_PARTITION_KEY = "log.publish.kafka.partition.key";
For new configurations, please define them in `Constants.Logging` instead.

2017-02-03 20:23 UTC, chtyim commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaLogAppender.java
> +  private static final String KAFKA_PARTITION_KEY_PROGRAM = "program";
Better use enum to define both `program` and `application`

2017-02-06 21:10 UTC, maochf commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
> +          Assert.assertTrue("Only one partition should have application logging context", isPresent);
No need to `assertTrue` since `isPresent` is always true here

2017-02-07 03:19 UTC, chtyim commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaLogAppender.java
> +    if (cConf.get(Constants.Logging.LOG_PUBLISH_PARTITION_KEY).equals(PartitionType.PROGRAM.getType()) ||
You can just leverage the enum name and a switch case.

```java
enum PartitionType {
  PROGRAM,
  APPLICATION;
}
...

if (NamespaceId.SYSTEM.getNamespace().equals(namespaceId)) {
  return loggingContext.getLogPartition();
}

switch (PartitionType.valueOf(cConf.get(Constants.Logging.LOG_PUBLISH_PARTITION_KEY))) {
  case PROGRAM:
    return loggingContext.getLogPartition();
  case APPLICATION:
  return namespaceId + ":" + loggingContext.getSystemTagsMap().get(ApplicationLoggingContext.TAG_APPLICATION_ID).getValue();
```

2017-02-07 03:19 UTC, chtyim commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaLogAppender.java
> +    if (cConf.get(Constants.Logging.LOG_PUBLISH_PARTITION_KEY).equals(PartitionType.PROGRAM.getType()) ||
Also, it's worth to add a check in the `ConfigurationCheck` class to make validation using the `PartitionType.valueOf()` call.

2017-02-07 23:07 UTC, CuriousVini commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/kafka/TestKafkaLogging.java
> +          Assert.assertTrue("Only one partition should have application logging context", isPresent);
fixed

2017-02-07 23:35 UTC, CuriousVini commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaLogAppender.java
> +    if (cConf.get(Constants.Logging.LOG_PUBLISH_PARTITION_KEY).equals(PartitionType.PROGRAM.getType()) ||
fixed

2017-02-07 23:35 UTC, CuriousVini commented
@chtyim Addressed comments and tested on cluster. Please take another look when you get a chance, thanks

2017-02-08 00:03 UTC, chtyim commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/kafka/KafkaLogAppender.java
> +        return null;
Should throw instead of returning `null`.

2017-02-08 00:03 UTC, chtyim commented
Just one comment left, the rest LGTM

2017-02-08 00:22 UTC, CuriousVini commented
will squash and merge once build passes

2017-02-08 01:50 UTC, CuriousVini commented
Build failed for `HBaseTableCoprocessorTestRun`. Rerunning build: http://builds.cask.co/browse/CDAP-RUT473-6

2017-02-09 01:46 UTC, CuriousVini commented
Resolved conflicts. Rerunning build: http://builds.cask.co/browse/CDAP-RUT473-10

2017-02-10 00:58 UTC, CuriousVini commented
build passed. Merging.

2017-02-10 00:59 UTC, merged