CDAP-8180 Check node version in SDK
cdapio/cdap pull request #7786
Opened 2017-02-02 16:21 UTC by wolf31o2

This restores the checks in the SDK.

- Only remove `__pidfile` on successful stop
- Correct `cdap_status_pidfile` checking in `cdap_check_pidfile` (is this function even necessary?)
- Restore use of `cdap_sdk_check_before_start` for Node.js checks

2017-02-02 23:25 UTC, dereklwood requested changes

2017-02-02 23:25 UTC, dereklwood commented on cdap-common/bin/functions.sh
> -      echo "${__label} running as PID ${__pid}. Stop it first."
In the case of running start while already running, the new output will be ``${__label} running as PID ${__pid}`` which can easily be misconstrued as a successful command.

Maybe add equivalent output where this is called, ie https://github.com/caskdata/cdap/blob/a4d03ef1922cb6ac145bd0f670a85d3a0c2e12ea/cdap-common/bin/functions.sh#L612

2017-02-02 23:29 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> -      echo "${__label} running as PID ${__pid}. Stop it first."
So suppress the `cdap_status_pidfile` output like was done here and give our own if it's running? I can see the confusion a little, but if I try a start while it's already running, the end result gives me what I wanted, a started CDAP Standalone. I'm kinda up in the air about this.

2017-02-02 23:40 UTC, dereklwood commented on cdap-common/bin/functions.sh
> -      echo "${__label} running as PID ${__pid}. Stop it first."
i was thinking leave the ``cdap_status_pidfile`` output (I'm assuming its called when you do "cdap status"), but just add an extra line for this case to indicate "already started, did you mean restart?".  Weird I know... i'm on the fence as well, but i can imagine someone not realizing its stopped, running start and thinking they have just restarted.

2017-02-03 00:17 UTC, sreevatsanraman commented on cdap-common/bin/functions.sh
> -      echo "${__label} running as PID ${__pid}. Stop it first."
Status should indicate the following:
- Process is running
- Process is stopped
- PID file exists but the process is not running

2017-02-03 00:27 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> -      echo "${__label} running as PID ${__pid}. Stop it first."
Ehh, status most definitely should not say "stop it first" anywhere. We are discussing the behavior when a start is attempted while we're already running, which is what's handled here.

2017-02-03 00:30 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> -      echo "${__label} running as PID ${__pid}. Stop it first."
Also, what do we do for other cases? PID file exists but process isn't running? Should we start? Error out?

2017-02-03 17:44 UTC, wolf31o2 commented
Added more output in `cdap_check_pidfile` to give the user a better experience.

2017-02-03 18:43 UTC, dereklwood approved these changes

2017-02-03 18:44 UTC, dereklwood commented
👍 lgtm

2017-02-06 17:44 UTC, wolf31o2 commented
Rebased/squashed/pushed... merging.

2017-02-06 17:44 UTC, merged