[CDAP-8341] Create namespace tmp/ streams/[.deleted/ dirs with same group and permissions as data/
cdapio/cdap pull request #7841
Opened 2017-02-07 00:28 UTC by anew

This is because otherwise, with per-app impersonation, the first program that runs (or the first stream that is created) will create them, and depending on the permissions:
- that will fail because the app user has no permissions
- that will succeed but then the next app will fail because it has no permissions

Therefore we must create these directories ahead of time, with group write for the group that is configured for the namespace. 

Logic is exactly the same as the existing logic for the data/ directory. Hence refactoring a little to avoid code duplication.

2017-02-07 07:41 UTC, anew commented
Build passed: http://builds.cask.co/browse/CDAP-DUT5429-1

2017-02-07 22:43 UTC, Nishith requested changes

2017-02-07 22:43 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
> +        throw new IOException(String.format("Error while creating %s directory '%s' for namespace '%s': %s",
This will be caught by the outer catch and be needlessly nested. Refactor to avoid nesting?

2017-02-07 22:43 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
> +        if (groupToSet != null) {
Perhaps add a comment about what happens if the UGI does not return a group?

2017-02-08 02:53 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
> +          // attempt to determine the current user's primary group. Note taht we cannot use ugi.getPrimaryGroup()
s/taht/that

2017-02-08 02:53 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
> +          // that there is not guarantee that getGroupNames() returns anything.
s/not/no

2017-02-08 02:55 UTC, Nishith commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
> +      if (location.mkdirs()) {
return location.mkdirs()?

2017-02-08 02:56 UTC, Nishith reviewed
A couple of minor comments. LGTM otherwise.

2017-02-08 02:57 UTC, Nishith approved these changes

2017-02-08 07:17 UTC, anew commented
squash, rebase and merge. now.

2017-02-08 07:18 UTC, merged