Bugfix release/version bump
cdapio/cdap pull request #7888
Opened 2017-02-08 23:28 UTC by CuriousVini

2017-02-08 23:31 UTC, albertshau commented on cdap-ui/templates/apps/predefined/TwitterToStream.json
> +        "version": "4.0.2-SNAPSHOT"
@ajainarayanan are these templates still used?

2017-02-08 23:40 UTC, CuriousVini commented
@wolf31o2 @awholegunch  I have made changes to cdap version in cdap-distributions/bin/build_docs_bucket.sh which were overridden by https://github.com/caskdata/cdap/commit/45a0588648ac2a101f80b28db91e7791d8e207de#diff-e5440dc1aac6f2c9941f57ba9702959dL47.

2017-02-08 23:54 UTC, albertshau reviewed
pom and archetype changes lgtm, may want to check with others about the other changes.

2017-02-09 00:07 UTC, wolf31o2 requested changes
There's quite a few places where we're incorrectly putting snapshot into the version. SNAPSHOT only applies to Java code and Java artifacts. Everything that uses Chef requires Linux package versioning (a.b.c(.d)-r), which includes EMR, HDInsight, Docker, VM.

Thanks

2017-02-09 00:07 UTC, wolf31o2 commented on cdap-distributions/src/packer/files/cdap-sdk.json
> +    "version": "4.0.2-SNAPSHOT-1"
This can never have SNAPSHOT in it. We never release a SNAPSHOT set of packages. Packages have either 3 or 4 version components. Any 4.0.2 SNAPSHOT will be 4.0.2.$(date +%s) as the version.

2017-02-09 00:07 UTC, wolf31o2 commented on cdap-distributions/src/emr/install.sh
> +CDAP_TAG='v4.0.2-SNAPSHOT'
This will break EMR installation. This is the *RELEASE* tag. We don't tag snapshots.

2017-02-09 00:07 UTC, wolf31o2 commented on cdap-distributions/src/emr/install.sh
> +CDAP_VERSION=${CDAP_VERSION:-4.0.2-SNAPSHOT-1}
This cannot include SNAPSHOT.

2017-02-09 00:07 UTC, wolf31o2 commented on cdap-distributions/src/hdinsight/pkg/install.sh
> +CDAP_TAG='v4.0.2-SNAPSHOT'
This *must* be `v4.0.1` to match the Git tag.

2017-02-09 00:07 UTC, wolf31o2 commented on cdap-distributions/src/hdinsight/pkg/install.sh
> +CDAP_VERSION='4.0.2-SNAPSHOT-1'
This cannot have SNAPSHOT.

2017-02-09 00:07 UTC, wolf31o2 commented on cdap-distributions/src/hdinsight/pkg/mainTemplate.json
> +        "uri": "http://downloads.cask.co/hdinsight/install-4.0.2-SNAPSHOT.sh",
No SNAPSHOT on either of these.

2017-02-09 00:07 UTC, wolf31o2 commented on cdap-ui/package.json
> +  "version": "4.0.2-SNAPSHOT",
I'm pretty sure Node packages shouldn't contain SNAPSHOT.

2017-02-09 02:05 UTC, wolf31o2 approved these changes
Changes LGTM

2017-02-09 02:26 UTC, merged