Close files after configurable time in rolling appender
cdapio/cdap pull request #8053
Opened 2017-02-18 21:44 UTC by CuriousVini

Issue: https://issues.cask.co/browse/CDAP-8613
Build:

2017-02-19 00:00 UTC, CuriousVini commented
Build is green

2017-02-21 00:01 UTC, gsps1 requested changes
few comments

2017-02-21 00:01 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/LocationManager.java
> +        iter.remove();
remove before closing, so if there is an exception, we wont be having a reference to output stream that can be in a bad state.

2017-02-21 00:01 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/LocationManager.java
> +                         String filePermissions, long fileCloseInterval) {
we should call this something like `fileMaxInactiveTimeInSeconds`

2017-02-21 00:01 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/LocationOutputStream.java
> +  public LocationOutputStream(Location location, OutputStream outputStream, long modifiedTimestamp) {
call this `lastWriteTimestamp`

2017-02-21 00:01 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/RollingLocationLogAppender.java
> +  public void setFileCloseInterval(long fileCloseInterval) {
add javadocs with unit of time. etc

2017-02-21 00:08 UTC, CuriousVini commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/RollingLocationLogAppender.java
> +  public void setFileCloseInterval(long fileCloseInterval) {
I have added it in sample xml and not here because this is logback config and we have not added javadocs for it.

2017-02-21 00:08 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/LocationManager.java
> +        OutputStream outputStream = new LocationOutputStream(logFile, logFile.getOutputStream(),
we also need to pass permissions when we do getOutputStream. look at https://github.com/caskdata/cdap/pull/8044

2017-02-21 00:09 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/RollingLocationLogAppender.java
> +  public void setFileCloseInterval(long fileCloseInterval) {
so ? its for clarity right. so we know what the property is etc.

2017-02-21 08:14 UTC, gsps1 reviewed
mostly nits, one main comment about test case sleep.

2017-02-21 08:14 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/LocationOutputStream.java
> +  public long getModifiedTimestamp() {
change this to lastWriteTimestamp as wel

2017-02-21 08:14 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/LocationManager.java
> +                                                                         logFile.getOutputStream(filePermissions),
nit: indent

2017-02-21 08:14 UTC, gsps1 commented on cdap-watchdog/src/main/java/co/cask/cdap/logging/plugins/RollingLocationLogAppender.java
> +    if (locationManager != null) {
you are not doing the null check in flush btw.

2017-02-21 08:14 UTC, gsps1 commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/plugins/RollingLocationLogAppenderTest.java
> +    Thread.sleep(TimeUnit.MINUTES.toMillis(1));
sleeping for one minute ? that's bad, have lower time interval.

2017-02-21 08:18 UTC, CuriousVini commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/plugins/RollingLocationLogAppenderTest.java
> +    Thread.sleep(TimeUnit.MINUTES.toMillis(1));
what is the suggested time?

2017-02-21 21:04 UTC, gsps1 commented on cdap-watchdog/src/test/java/co/cask/cdap/logging/plugins/RollingLocationLogAppenderTest.java
> +    Thread.sleep(TimeUnit.MINUTES.toMillis(1));
set the file inactive time to be 200 milli seconds instead of 20 seconds in the test. sleep for like 500 milliseconds and then perform the check.

2017-02-21 21:15 UTC, gsps1 commented
lgtm, squash and merge.

2017-02-22 00:23 UTC, CuriousVini commented
Build is green. merging

2017-02-22 00:23 UTC, merged