[TRACKER-282] - Fix when explore is disabled, the preview tab in Tracker keeps spinning.
cdapio/cdap pull request #8247
Opened 2017-03-01 13:47 UTC by sushiladokar

https://issues.cask.co/browse/TRACKER-282

2017-03-02 22:07 UTC, ajainarayanan requested changes

2017-03-02 22:07 UTC, ajainarayanan commented on cdap-ui/app/tracker/controllers/preview-ctrl.js
> +        console.log('Error', err);
We show appropriate message. We can remove this console.log statement.

2017-03-02 22:07 UTC, ajainarayanan commented on cdap-ui/app/tracker/controllers/preview-ctrl.js
> +    let query = 'SELECT * FROM ' + this.entityType + '_' + this.$state.params.entityId + ' LIMIT 500';
This query is incorrect. We should use the `ExploreTablesStore` to get the database name and table name. Please refer Explore Fast action in the react code base

2017-03-02 22:07 UTC, ajainarayanan commented on cdap-ui/app/tracker/templates/preview.html
>    <p>No data</p>
Would this show both `No data` and the `Preview is not available for this ...` message?

2017-03-02 22:09 UTC, ajainarayanan commented on cdap-ui/app/tracker/controllers/preview-ctrl.js
> +    let query = 'SELECT * FROM ' + this.entityType + '_' + this.$state.params.entityId + ' LIMIT 500';
`ExploreTablesStore` needs to be exported via `common/cask-header.js` and then used here via `window` object.

2017-03-03 12:43 UTC, sushiladokar commented on cdap-ui/app/tracker/templates/preview.html
>    <p>No data</p>
Preview message will be shown only when **previewNotAvailable** gets true and when it gets true, this  means error occurred while executing query and hence **previewData** will be undefined and its length won't be equal to zero. 

On the other hand **previewNotAvailable** wont get true if query is successful and even when we have empty data.

2017-03-03 15:37 UTC, sushiladokar commented on cdap-ui/app/tracker/controllers/preview-ctrl.js
> +    let query = 'SELECT * FROM ' + this.entityType + '_' + this.$state.params.entityId + ' LIMIT 500';
Tried exporting ExploreTablesStore  and calling window.CaskCommon.ExploreTablesStore.getState() but its returning empty array of tables.
Do I also need to import ActionCreater here and call fetchTables method to get the tables list or am I missing something here ?

2017-03-25 02:42 UTC, ajainarayanan commented
The change doesn't fix the infinite spinning issue.

2017-03-25 06:30 UTC, nitinmotgi commented
What are we doing with this PR ? Close it incomplete then atleast.

2017-03-29 01:37 UTC, ajainarayanan commented
Closing this for now as it is of lower priority. Will reopen again with appropriate fix.

2017-03-29 01:37 UTC, closed without merging