CDAP-8889 Document live info endpoint
cdapio/cdap pull request #8297
Opened 2017-03-07 22:47 UTC by awholegunch

2017-04-03 20:05 UTC, poornachandra requested changes
@awholegunch Just a couple of comments.

2017-04-03 20:05 UTC, poornachandra commented on cdap-docs/reference-manual/source/http-restful-api/monitor.rst
> +first container listed being the CDAP Master::
first container listed being the active CDAP Master in a HA setup.

2017-04-03 20:05 UTC, poornachandra commented on cdap-docs/reference-manual/source/http-restful-api/monitor.rst
> +                    {"type":"system_service","name":"appfabric","host":"host1.example.com"},
It would be good to format this as -
```
{
   "host": "host1.example.com",
   "name": "appfabric",
   "type": "system_service"
}
```

2017-04-04 18:47 UTC, awholegunch commented on cdap-docs/reference-manual/source/http-restful-api/monitor.rst
> +first container listed being the CDAP Master::
Fixed.

2017-04-04 18:52 UTC, awholegunch commented on cdap-docs/reference-manual/source/http-restful-api/monitor.rst
> +                    {"type":"system_service","name":"appfabric","host":"host1.example.com"},
fixed.

2017-04-07 01:21 UTC, poornachandra approved these changes

2017-04-07 22:32 UTC, merged