Renamed UI README to BUILD.rst. Added more content to README.
cdapio/cdap pull request #8337
Opened 2017-03-13 20:26 UTC by bdmogal

2017-03-14 15:08 UTC, wolf31o2 requested changes
One minor change and a question

2017-03-14 15:08 UTC, wolf31o2 commented on cdap-ui/README.rst
> +  $ cd $(CDAP_HOME}
${

2017-03-14 15:08 UTC, wolf31o2 commented on cdap-ui/README.rst
> +* WRANGLER-54 - Added click-through experience for filling null or empty cells in Data Preparation
Should these be links to the issues?

2017-03-14 21:53 UTC, elfenheart commented on cdap-ui/BUILD.rst
> +  - `v4.5.0 Download <https://nodejs.org/download/release/v4.5.0/>`__
let's not suggest this. Downloading from this can cause folder permission issue. Let's just suggest `NVM`

2017-03-14 22:11 UTC, bdmogal commented on cdap-ui/BUILD.rst
> +  - `v4.5.0 Download <https://nodejs.org/download/release/v4.5.0/>`__
I just renamed this file. Can we fix it in a follow up? Otherwise give me the instructions, and I'm happy to do it

2017-03-22 14:37 UTC, bdmogal commented
@awholegunch has reviewed this via #8406. Merging.

2017-03-22 14:37 UTC, merged