Detect HDP 2.2+ and automatically append -Dhdp.version if not set
cdapio/cdap pull request #8445
Opened 2017-03-28 21:09 UTC by wolf31o2

Automatically detect HDP version on HDP 2.2+ and insert it into our CDAP Master command line, if it is not already present in OPTS variable. If the property is set in OPTS, use OPTS version, but output WARN on any version mismatches.

2017-03-29 00:01 UTC, dereklwood requested changes

2017-03-29 00:01 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +        local __my_hdp_version=$(echo ${OPTS} | grep -oP '\-Dhdp.version=\d+\.\d+\.\d+\.\d+-\d*' | cut -d= -f2)
last ``\d*`` should be ``\d+``, otherwise it could match ``2.2.6.0-``

2017-03-29 00:01 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +          logecho "[WARN] Using configured HDP version: ${__my_hdp_version}"
style-wise, should these all be one line?  Not a blocker but seems like a lot of log lines...

2017-03-29 14:56 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +          logecho "[WARN] Using configured HDP version: ${__my_hdp_version}"
I dropped it to two.

2017-03-29 14:57 UTC, wolf31o2 commented
@dereklwood updated and made a loop, so I could include IOP, as they're functionally the same here

2017-04-19 23:59 UTC, dereklwood requested changes

2017-04-19 23:59 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +        local __auto_version=$(${__dist}-select status hadoop-client | '{print $3}')
`awk` ... pls retest. otherwise logic lgtm

2017-04-19 23:59 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +            logecho "[WARN] ${__dist^^} version mismatch! Detected: ${__auto_version}, Configured: ${__conf_version}"
uppercase syntax only available in bash 4.0... ie doesn't work on my mac.  any compatibility concerns?  potential future bug if sdk starts using this function.

2017-04-20 15:45 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +            logecho "[WARN] ${__dist^^} version mismatch! Detected: ${__auto_version}, Configured: ${__conf_version}"
There aren't really any concerns. However, this is the only use of a bash 4+ feature and it's only for output, so I'll replace it with a little awk.

2017-04-20 15:46 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +        local __auto_version=$(${__dist}-select status hadoop-client | '{print $3}')
Yeah, I messed that up in the second commit. Fixing.

2017-04-20 18:00 UTC, dereklwood approved these changes

2017-04-21 16:32 UTC, merged