CDAP-1609 CDAP-9251 CDAP-8948 Add get/list schedule handler, test cas…
cdapio/cdap pull request #8484
Opened 2017-04-05 02:06 UTC by rohitsinha54

…es for add/update/get/delete schedule and bugfixes

### CDAP-1609
- Add get schedule api
- Add list schedules api
- Add unit tests for add/update/delete/get/list schedules

### CDAP-9251
- If the cron expression of schedule is invalid throw BadRequest for 40x response code rather than  IllegalArgumentException causing 50x response code

### CDAP-8948
- If the given programType is not Schedulable throw BadRequest for 40x response code rather than  IllegalArgumentException causing 50x response code

2017-04-05 17:59 UTC, Denton-L requested changes
Logic seems fine to me, just a few nitpicks about docs and code styling.

2017-04-05 17:59 UTC, Denton-L commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +      // SchedulableProgramType just wrap is in BadRequest to send proper error code to user if this call is made from
wrap is -> wrap it

2017-04-05 17:59 UTC, Denton-L commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
> +                                         ", app id: " + id.getApplication());
nit: should be aligned with the quotes of the previous line

2017-04-05 17:59 UTC, Denton-L commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +    return  doPut(getVersionedAPIPath(path, namespace), GSON.toJson(scheduleSpec));
nit: shouldn't be two spaces after the return

2017-04-05 17:59 UTC, Denton-L commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +    return  doPost(getVersionedAPIPath(path, namespace), GSON.toJson(scheduleSpec));
nit: shouldn't be two spaces after the return

2017-04-05 17:59 UTC, Denton-L commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
> +    return  doDelete(getVersionedAPIPath(path, namespace));
nit: shouldn't be two spaces after the return

2017-04-05 17:59 UTC, Denton-L commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +   * Gets all the the schedules in a application
Gonna do JJ's job; this sentence should end with a period.

2017-04-05 17:59 UTC, Denton-L commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +   * @return List of {@link ScheduleSpecification} of all the schedules in the application
L in List should be lowercase.

2017-04-05 18:21 UTC, rohitsinha54 commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
> +                                         ", app id: " + id.getApplication());
Its auto aligned. I think its making it inside ( Look at all the ones above.

2017-04-05 18:30 UTC, Denton-L commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
> +                                         ", app id: " + id.getApplication());
I see; my mistake!

2017-04-05 18:30 UTC, Denton-L approved these changes

2017-04-05 18:31 UTC, Denton-L commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +   * Gets all the the schedules in a application.
Sorry, one more; change "the the" to "of the".

2017-04-05 18:36 UTC, rohitsinha54 commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +   * Gets all the the schedules in a application.
👍

2017-04-06 04:05 UTC, rohitsinha54 commented
Random build failure here http://builds.cask.co/browse/CDAP-RUT857-3 
Running another time. Will merge as soon as it passes.

2017-04-06 06:37 UTC, merged