CDAP-1609 Schedule update without all fields of spec
cdapio/cdap pull request #8500
Opened 2017-04-06 06:46 UTC by rohitsinha54

Issue: https://issues.cask.co/browse/CDAP-1609
Build:

2017-04-06 07:04 UTC, chtyim commented
I don't see any big issue in the change. @poornachandra should also take a look as he is more familiar with the functionality.

2017-04-07 02:00 UTC, poornachandra requested changes
@rohitsinha54 A couple of comments

2017-04-07 02:00 UTC, poornachandra commented on cdap-proto/src/main/java/co/cask/cdap/proto/ScheduleUpdateDetail.java
> +  private final String scheduleDescription;
It would be good to keep the structure the same as schedule specification

2017-04-07 02:00 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +  private Map<String, String> getUpdatedProperties(Map<String, String> existing, Map<String, String> updated) {
It would be good to not merge the properties, and instead replace the properties. This will enable us to delete properties.

2017-04-07 02:00 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +                                                      "details %s. These configuration will be ignored due to type " +
The statement that says ignore can be removed.

2017-04-07 02:00 UTC, poornachandra commented on cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
> +                                                      "This configuration will be ignored due to type mismatch.",
The statement that says ignore can be removed.

2017-04-07 05:31 UTC, rohitsinha54 commented
@poornachandra : Review comments. Please have another look

2017-04-07 22:08 UTC, sagarkapare commented
Verified that comments from @poornachandra are addressed. Only one small additional comment about comment in the last commit. Rest LGTM 👍

2017-04-07 22:10 UTC, sagarkapare commented on cdap-proto/src/main/java/co/cask/cdap/proto/ScheduleUpdateDetail.java
> +  public Schedule getSchedule() {
please add javadoc when this would be `null`

2017-04-07 23:34 UTC, merged