Release Notes 4.1.1
cdapio/cdap pull request #8575
Opened 2017-04-14 18:34 UTC by awholegunch

Building as a Quick Build: https://builds.cask.co/browse/CDAP-DQB337-1

Page of interest: _tbc_

2017-04-14 18:54 UTC, awholegunch commented
Re-running build after fixing MD5 checksum.

2017-04-14 21:09 UTC, bdmogal commented
Known issue - https://issues.cask.co/browse/CDAP-9388

2017-04-14 21:20 UTC, awholegunch commented
Re-running build: https://builds.cask.co/browse/CDAP-DQB337-3

2017-04-15 01:26 UTC, Nishith commented on cdap-docs/vars
> +GIT_CDH_VERSIONS="5.1 through 5.11"
5.11 is not out yet though.

2017-04-15 01:26 UTC, Nishith commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9281` - Added support for CDH 5.11.0.
5.11 is not out. Although we tested on pre-release there is still a chance that things could break with the release version although highly unlikely. @bdmogal @sreevatsanraman Opinion?

2017-04-15 01:26 UTC, Nishith commented on cdap-docs/reference-manual/source/release-notes.rst
> +  arbitrary Spark code at the start or end of a pipeline.
s/start/beginning/?

2017-04-15 01:26 UTC, Nishith commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9242` - Improved the documentation for PartitionedFileSet properties.
s/PartitionedFileSet/PartitionedFileSet's?

2017-04-15 01:26 UTC, Nishith commented on cdap-docs/reference-manual/source/release-notes.rst
> +  the CDAP Studio UI. Users can now open a wrangler transform, wrangle the data, and save it
We are using both names, wrangler and data prep?

2017-04-15 01:26 UTC, Nishith commented on cdap-docs/reference-manual/source/release-notes.rst
> +  the CDAP Studio UI. Users can now open a wrangler transform, wrangle the data, and save it
Also, we are using both Data Preparation and Data Prep. Make that consistent?

2017-04-15 01:26 UTC, Nishith commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1364` - Removed the "__ui__" property which was being used only by
Is the formatting for the property name correct?

2017-04-15 02:13 UTC, sreevatsanraman commented on cdap-docs/vars
> +GIT_CDH_VERSIONS="5.1 through 5.11"
Mark it as 5.10 for now. Once the CDH release is out, we can update this.

2017-04-15 03:18 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1364` - Removed the "__ui__" property which was being used only by
Yes, though it could be shown as a literal (`__ui__`):
```
``__ui__``

2017-04-15 03:19 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9242` - Improved the documentation for PartitionedFileSet properties.
I would change it to "of PartitionedFileSet properties" if anything.

2017-04-15 03:21 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +  the CDAP Studio UI. Users can now open a wrangler transform, wrangle the data, and save it
To be honest, I don't know. I have not used it to know what is being shown where. It seems to me that the plugin is called wrangler, and in the docs were are going to use both Data Preparation (Data Prep) for short.

2017-04-15 03:21 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +  arbitrary Spark code at the start or end of a pipeline.
Sure.

2017-04-15 03:21 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9281` - Added support for CDH 5.11.0.
ibid.

2017-04-15 03:23 UTC, awholegunch commented on cdap-docs/vars
> +GIT_CDH_VERSIONS="5.1 through 5.11"
Fixed.

2017-04-15 03:26 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +  the CDAP Studio UI. Users can now open a wrangler transform, wrangle the data, and save it
I have change "Data Prep" to "Data Preparation", and "Data Preparation" to "Data Preparation (Wrangler)" when talking about the plugin.

2017-04-15 03:27 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9242` - Improved the documentation for PartitionedFileSet properties.
Changed to "of"

2017-04-15 03:29 UTC, awholegunch commented
Building as a Quick Build: https://builds.cask.co/browse/CDAP-DQB337-4

2017-04-15 03:56 UTC, prinam commented
Please add the following JIRAs:

2017-04-15 04:04 UTC, awholegunch commented
Building as a Quick Build: https://builds.cask.co/browse/CDAP-DQB337-5

2017-04-15 09:12 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9250` - Added support for the Hive version shipped with HDP 2.6.
Added support for HDP 2.6

2017-04-15 09:13 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8902` - Added support for adding, deleting, updating, and retrieving
More than CLI. It is a feature that we added that should be mentioned. ```Added support for adding, deleting, updating schedules.```

2017-04-15 09:14 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9147` - Added pipeline start and finish logs in the condensed view.
Not important. Remove this.

2017-04-15 09:14 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9327` - Added support in the CDAP UI for the Spark program pipeline
Not important remove. It is a feature as a whole that matters and no need to call it out separately for backend changes and UI changes.

2017-04-15 09:15 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-7352` - Improved log viewer to always show headers at the top of the
Not super critical. Leave out.

2017-04-15 09:16 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8982` - Updated SDK images (Amazon AMI, Docker image, Virtual Machine
Not important. leave out.

2017-04-15 09:17 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9003` - Increased the memory allocation for the CDAP Explore service
Increased the default memory ....

2017-04-15 09:18 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9070` - Added the ability to work with Data Preparation from within
Don't call it out in multiple places. We can just say it once. SO drop this.

2017-04-15 09:18 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9242` - Improved the documentation of PartitionedFileSet properties.
Remove this.

2017-04-15 09:20 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9282` - Made the AppMetadataStore and ScheduleStore compatible with an
Combine 9282 and 9283 into one Upgrade imporvements. Main thing to highlight here is that we can have very minimal downtime for upgrades. @poornachandra - can you comment on the text needed?

2017-04-15 09:20 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1432` - Added a timer for realtime preview to stop a run
Not important. remove.

2017-04-15 09:21 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8668` - Modified the log viewer to only show ERROR, WARN, and INFO
Remove.

2017-04-15 09:22 UTC, sreevatsanraman commented
@awholegunch - please address the comments.

2017-04-15 09:26 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9282` - Made the AppMetadataStore and ScheduleStore compatible with an
```Improved the CDAP upgrade procedure to minimize the downtime needed by performing data migration in the background```

2017-04-15 09:32 UTC, sreevatsanraman commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1364` - Removed the ``__ui__`` property which was being used only by
Remove this.

2017-04-15 14:53 UTC, bdmogal requested changes
@awholegunch did one pass. Will do another pass after the current comments are addressed.

1. After the current comments are addressed, let's order this list by importance. I can help with this.
2. There are so many changes unrelated to 4.1.1 in this PR? Do they need a review?

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8872` - Changed the Apache Tephra dependency to the 0.11.0-incubating
Upgraded  Apache Tephra dependency to...

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +  to the Kafka Consumer Flowlet.
What is the Kafka Consumer Flowlet? Part of the kafka-pack? I don't think this is a new feature. Let's move it to improvements?

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9141` - Added a 'sparkprogram' plugin type that can be used to run
Let's add "An external spark program can be added by clicking the plus button on the CDAP UI, choosing Library, and specifying 'sparkprogram' as the type. It is then available as an Action plugin in the CDAP Studio."

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9327` - Added support in the CDAP UI for the Spark program pipeline
Yup, let's club it with the previous one

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1316` - Added the ability to see logs in preview.
Logs for previews of CDAP pipelines are now available in the UI via the Logs button in Preview mode.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`WRANGLER-51` - Added Copy Column to the list of column dropdown directives
Remove

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`WRANGLER-77` - Added a column-action dropdown menu for Data Preparation
Let's expand this:

``Added point-and-click interactions for applying directives such as parsing, splitting, find and replace, filling null or empty rows, copying and deleting columns in Data Preparation. They can be invoked by using the dropdown menu for every column.``

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9235` - Added workspace tabs to the top panel of the Data Preparation (Wrangler) plugin.
``Users can now interact with and manage multiple workspaces in Data Preparation``

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9235` - Added workspace tabs to the top panel of the Data Preparation (Wrangler) plugin.
Also, let's move it closer to other Data Preparation release notes

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8430` - Modified the Entity list page to show appropriate message when
appropriate is repeated. Also its the Overview page

``Users can now see an contextual message with appropriate call(s) to action when no entities are found on the Overview page.``

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +  property specified in the configuration of application.
... the application?

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8990` - New configurations have been added to control the YARN
turn into active voice? Added new configurations...

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9282` - Made the AppMetadataStore and ScheduleStore compatible with an
Lets not have CDAP class names in here

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9283` - The migration of ScheduleStore and AppMetadataStore from the
remove/combine with the last one without class names

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9311` - Adding support for service discovery in plugins.
How can users use it?

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9311` - Adding support for service discovery in plugins.
Also, seems like a new feature

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9371` - Added convenience functions to set a Date in a
not sure its important

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-4213` - Fixed an issue in the CDAP startup script for Windows,
I think this first part is unnecessary. The actual problem is on the next line.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-6348` - Fixed a Issue in Namespace delete which caused CDAP
lower case ``I``

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-7138` - Fixed a problem with duplicate log lines showing for a running
Fixed a problem that caused duplicate logs to show up for a running pipeline

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8396` - Added a "call-to-action" when the user had successfully
remove

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8396` - Added a "call-to-action" when the user had successfully
calls to action were added in 4.1, in which we specifically called them out. Let's not have just this one here.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8013` - Disabled the write-to-any-dataset for sinks when in preview.
When previewing a pipeline in the CDAP Studio, disabled all writes to sinks. Incoming data to sinks can be viewed in the preview tab of the sink, but is not written to the sink.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8888` - Fixed an issue with the YARN container allocation logic so
``Yarn``

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9005` - Fixed an issue where the HBaseQueueDebugger failed when
... where the HBase Queue Debugging Tool failed ...

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +  in the CDAP Sentry Extension.
Let's make the user the subject of a release note, not a CDAP component.

``Users can now for grant and revoke privileges for Unix groups and users when using Apache Sentry as the authorization extension for CDAP``

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +  in the CDAP Sentry Extension.
Also, this seems like an improvement

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9029` - Fixed an issue where the CDAP Sentry Extension failed to grant
remove, unless we can provide more specifics

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9035` - Fixed an issue where the CDAP Sentry Extension was not able to
let's make the user the subject, not the CDAP extension, just like before.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9084` - LogHandler endpoints now return a 404 status code if the
The CDAP Logs APIs now return...

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9114` - Fixed an issue with the retrying of local dataset operations
we just added retry for local dataset operations right? Let's just say that?

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9160` - Fixed a memory leak issue with the Hadoop FileSystem object.
how does this impact a user? also, Apache Hadoop

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9247` - Removed a misleading error log message in the CDAP Explore
remove

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9314` - Made a StructuredRecord serializable by Kryo in a Spark
this was already mentioned before. Or something related. Let's remove?

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-703` - Improved DB Plugin Get Schema error messaging.
Improved error messages for the 'Get Schema' functionality of Database plugins in CDAP Pipelines.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9333` - Fixed an issue where preview did not show data for successful
preview of CDAP pipelines

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1453` - Fixed an issue that prevented batch pipelines with a
Allowed CDAP pipelines with a single action plugin to now be deployed. This feature can be used to run external Apache Spark programs as CDAP pipelines.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1453` - Fixed an issue that prevented batch pipelines with a
Also, let's club this with the ``sparkprogram`` related items above.

2017-04-15 14:53 UTC, bdmogal commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1468` - Fixed an issue where the CDAP UI shows a success message
remove

2017-04-15 15:16 UTC, bdmogal commented
Top 5 things in 4.1.1:
1. Data Preparation: Point-and-click interactions and integration with pipelines
2. Upgrade: Significant reduction in downtime during CDAP upgrades, by reducing some data migration and doing required migration in the background after CDAP starts up.
3. Pipeline Previews: Added logs, better error messaging, ability to read from existing datasets, better stop experience.
4. Logs: Added a condensed view of logs for CDAP pipelines and programs that does not include logs emitted by the CDAP platform and libraries. It only contains lifecycle logs, logs emitted by the program/pipeline and errors.
5. Schedules: Ability to update them without redeploying the application.

Everything else can follow, but these five need to be called out as the first 5 things in release notes. Also, let's group new features under these 5 categories, just like we did for 4.1.0.

@sreevatsanraman let me know if I missed anything, or if you disagree with the order.

2017-04-15 15:18 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9250` - Added support for the Hive version shipped with HDP 2.6.
Fixed.

2017-04-15 15:19 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8902` - Added support for adding, deleting, updating, and retrieving
Fixed.

2017-04-15 15:20 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9147` - Added pipeline start and finish logs in the condensed view.
Fixed.

2017-04-15 15:20 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9327` - Added support in the CDAP UI for the Spark program pipeline
Fixed.

2017-04-15 15:21 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-7352` - Improved log viewer to always show headers at the top of the
Fixed.

2017-04-15 15:21 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8982` - Updated SDK images (Amazon AMI, Docker image, Virtual Machine
Fixed.

2017-04-15 15:22 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9003` - Increased the memory allocation for the CDAP Explore service
Fixed.

2017-04-15 15:22 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9070` - Added the ability to work with Data Preparation from within
Fixed.

2017-04-15 15:22 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9242` - Improved the documentation of PartitionedFileSet properties.
Fixed.

2017-04-15 15:24 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9282` - Made the AppMetadataStore and ScheduleStore compatible with an
Fixed.

2017-04-15 15:24 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1432` - Added a timer for realtime preview to stop a run
Fixed.

2017-04-15 15:24 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8668` - Modified the log viewer to only show ERROR, WARN, and INFO
Fixed.

2017-04-15 15:25 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1364` - Removed the ``__ui__`` property which was being used only by
Fixed.

2017-04-15 15:26 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8872` - Changed the Apache Tephra dependency to the 0.11.0-incubating
Fixed.

2017-04-15 15:26 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +  to the Kafka Consumer Flowlet.
Moved.

2017-04-15 15:29 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9141` - Added a 'sparkprogram' plugin type that can be used to run
Added.

2017-04-15 15:32 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1316` - Added the ability to see logs in preview.
Fixed.

2017-04-15 15:36 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9235` - Added workspace tabs to the top panel of the Data Preparation (Wrangler) plugin.
Fixed, but not sure where you want to move this.

2017-04-15 15:40 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`WRANGLER-77` - Added a column-action dropdown menu for Data Preparation
Fixed.

2017-04-15 15:41 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`WRANGLER-51` - Added Copy Column to the list of column dropdown directives
Fixed.

2017-04-15 15:42 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +  property specified in the configuration of application.
Fixed.

2017-04-15 16:08 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8430` - Modified the Entity list page to show appropriate message when
Fixed.

2017-04-15 16:10 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8990` - New configurations have been added to control the YARN
Fixed.

2017-04-15 16:10 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9283` - The migration of ScheduleStore and AppMetadataStore from the
Fixed.

2017-04-15 16:12 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-4213` - Fixed an issue in the CDAP startup script for Windows,
Fixed.

2017-04-15 16:13 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9371` - Added convenience functions to set a Date in a
Removed.

2017-04-15 16:13 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9311` - Adding support for service discovery in plugins.
Moved to new features section.

2017-04-15 16:14 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-6348` - Fixed a Issue in Namespace delete which caused CDAP
Edited to:
```
Fixed an issue with namespace deletion which caused CDAP
  Application test cases to fail earlier in a Windows environment.

2017-04-15 16:17 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-7138` - Fixed a problem with duplicate log lines showing for a running
Fixed.

2017-04-15 16:18 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8013` - Disabled the write-to-any-dataset for sinks when in preview.
Fixed.

2017-04-15 16:19 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8396` - Added a "call-to-action" when the user had successfully
Removed.

2017-04-15 16:21 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-8888` - Fixed an issue with the YARN container allocation logic so
No, it's "YARN": https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/YARN.html

2017-04-15 16:22 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9005` - Fixed an issue where the HBaseQueueDebugger failed when
Fixed.

2017-04-15 16:24 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +  in the CDAP Sentry Extension.
Moved and edited to:
```
Users can now grant and revoke privileges for UNIX groups and
  users when using Apache Sentry as the authorization extension for CDAP.

2017-04-15 16:27 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9029` - Fixed an issue where the CDAP Sentry Extension failed to grant
Combined with 9035.

2017-04-15 16:28 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9035` - Fixed an issue where the CDAP Sentry Extension was not able to
```
Fixed an issue where users could not grant and revoke privileges for UNIX groups and
  users when using Apache Sentry as the authorization extension for CDAP.

2017-04-15 16:30 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9084` - LogHandler endpoints now return a 404 status code if the
Edited and moved to *API Changes* section:
```
The CDAP Logging APIs now return a 404 status code if the
  entity (the run id) for which logs are requested does not exist.

2017-04-15 16:32 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9114` - Fixed an issue with the retrying of local dataset operations
Fixed.

2017-04-15 16:32 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9247` - Removed a misleading error log message in the CDAP Explore
Fixed.

2017-04-15 16:34 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9314` - Made a StructuredRecord serializable by Kryo in a Spark
Combined with "CDAP-8980": just added the link as a second issue resolved.

2017-04-15 16:35 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9333` - Fixed an issue where preview did not show data for successful
Fixed.

2017-04-15 16:35 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-703` - Improved DB Plugin Get Schema error messaging.
Fixed.

2017-04-15 16:36 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1468` - Fixed an issue where the CDAP UI shows a success message
Fixed.

2017-04-15 16:41 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`HYDRATOR-1453` - Fixed an issue that prevented batch pipelines with a
I rewrote it as:
```
Users can now deploy CDAP pipelines with a single action
  plugin. This feature can be used to run external Apache Spark programs as CDAP pipelines.
```
and then moved it into the *New Features* section.

What do you mean by *club*? Do you mean *group*? Or *delete*?

2017-04-15 16:59 UTC, awholegunch commented on cdap-docs/reference-manual/source/release-notes.rst
> +- :cask-issue:`CDAP-9160` - Fixed a memory leak issue with the Hadoop FileSystem object.
Rewrote as:
```
Fixed an issue when a user was using impersonation where YARN
  would kill a container due to excessive memory usage.
```

2017-04-15 17:23 UTC, awholegunch commented
Revised per comments. Rerunning building as a Quick Build: https://builds.cask.co/browse/CDAP-DQB337-6

Pages of interest: 
- Release Notes: https://builds.cask.co/artifact/CDAP-DQB337/shared/build-6/Docs-HTML/4.1.1-SNAPSHOT/en/reference-manual/release-notes.html#release-4-1-1
- Hadoop Compatibility: https://builds.cask.co/artifact/CDAP-DQB337/shared/build-6/Docs-HTML/4.1.1-SNAPSHOT/en/admin-manual/hadoop-compatibility.html

2017-04-15 18:09 UTC, awholegunch commented
Rerunning building as a Quick Build: https://builds.cask.co/browse/CDAP-DQB337-7

Pages of interest:

Release Notes: https://builds.cask.co/artifact/CDAP-DQB337/shared/build-7/Docs-HTML/4.1.1-SNAPSHOT/en/reference-manual/release-notes.html#release-4-1-1
Hadoop Compatibility: https://builds.cask.co/artifact/CDAP-DQB337/shared/build-7/Docs-HTML/4.1.1-SNAPSHOT/en/admin-manual/hadoop-compatibility.html

2017-04-15 18:13 UTC, sreevatsanraman commented
LGTM

2017-04-15 18:13 UTC, merged