CDAP-7217 Document creation of "cdap" user
cdapio/cdap pull request #8719
Opened 2017-05-05 23:09 UTC by awholegunch

Adds paragraphs on installing the "cdap" user on all nodes to packages and CM.
Adds to existing paragraph on MapR. 
Removes trailing whitespace.

Running as a Quick Build: _tbc_
Pages of interest: _tbc_

2017-05-18 19:44 UTC, mattwuenschel commented
LGTM 👍

2017-05-18 19:58 UTC, dereklwood requested changes

2017-05-18 19:58 UTC, dereklwood commented on cdap-docs/admin-manual/source/installation/cloudera.rst
> +**The CDAP system user:** As Hadoop resolves users at the NameNode, the ``cdap`` user must
I think this section would be more appropriate under "Preparing the cluster", and more consistent with the other installation methods.  Let me know if you disagree.  There is already a mention of the cdap user there (line 87) that should at least link to this section.

2017-05-18 19:58 UTC, dereklwood commented on cdap-docs/admin-manual/source/installation/cloudera.rst
> +activated on the cluster.
fine for now, but would be nice to know which of "distributed" or "activated" it is... i dont know so would have to test.

2017-05-18 19:58 UTC, dereklwood commented on cdap-docs/admin-manual/source/installation/packages.rst
> +- All services run as the ``cdap`` user installed by the package manager.
this is accurate, but seemingly contradicts the next section where it instructs users to create the CDAP user manually.  we probably just need to link to the below section, and add more explanation

2017-05-18 19:58 UTC, dereklwood commented on cdap-docs/admin-manual/source/installation/packages.rst
> +Create the "cdap" User
I think we need to preface this section with the fact that the base cdap package will install cdap as a system user. 
 However, for the reasons of consistent UIDs across the cluster, or ensuring it is created on the namenode when installing cdap elsewhere, you need to make sure the cdap user is installed consistently on all nodes of the cluster.

Users should be able to ascertain that the base package will install the cdap user automatically, and that is still an option for them (if on singlenode cluster, etc).

2017-05-19 22:25 UTC, awholegunch commented on cdap-docs/admin-manual/source/installation/cloudera.rst
> +activated on the cluster.
OK, will leave it as shown.

2017-05-19 22:27 UTC, awholegunch commented on cdap-docs/admin-manual/source/installation/packages.rst
> +- All services run as the ``cdap`` user installed by the package manager.
Added a link to the section `Create the "cdap" User`.

2017-05-19 22:37 UTC, awholegunch commented on cdap-docs/admin-manual/source/installation/cloudera.rst
> +**The CDAP system user:** As Hadoop resolves users at the NameNode, the ``cdap`` user must
No, that makes sense: I've moved it up to under `Preparing the Cluster > Create the "cdap" User`.

2017-05-19 22:53 UTC, awholegunch commented on cdap-docs/admin-manual/source/installation/packages.rst
> +Create the "cdap" User
See changes.

2017-05-19 23:09 UTC, dereklwood commented on cdap-docs/admin-manual/source/installation/packages.rst
> +Though the base CDAP package will automatically install the ``cdap`` system user, it's
it seems like this sentence is redundant now to above and below... but i'll leave it up to you

2017-05-19 23:10 UTC, dereklwood commented
minor suggestion, at your discretion.  otherwise 👍 lgtm

2017-05-19 23:10 UTC, dereklwood approved these changes

2017-05-19 23:39 UTC, merged