[CDAP-9025] Instead of admin users support admin groups, so that users can be add…
cdapio/cdap pull request #8866
Opened 2017-05-23 07:11 UTC by Nishith

…ed to the admin group to gain privileges and removed from the group if privilege revocation is required.

2017-05-30 17:50 UTC, sreevatsanraman commented on cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
> -      public static final String ADMIN_USERS = "security.authorization.admin.users";
Are we deprecating this property? Will this break backward compatibility?

2017-05-31 21:09 UTC, Nishith commented on cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
> -      public static final String ADMIN_USERS = "security.authorization.admin.users";
Discussed offline and decided to drop off this property as this is a security hole.

2017-06-01 05:38 UTC, Nishith commented
Build: https://builds.cask.co/browse/CDAP-RUT984-3

2017-06-01 06:26 UTC, rohitsinha54 requested changes
Some comments. Most importantly we need to make sure that we handle the upgrade properly. if admin.users was configured to user1,user2 and now if we drop this setting and introduce group one we need to handle the privilege which got granted to user1,user2.

2017-06-01 06:26 UTC, rohitsinha54 commented on cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
> -      public static final String ADMIN_USERS = "security.authorization.admin.users";
But removing it from here does not resolve security loophole or backward compatibility correct ? We can expect users to specify new groups who will have admin but what about admin.users who have already been granted access. Do we need to drop privileges for them ?

2017-06-01 06:26 UTC, rohitsinha54 commented on cdap-security/src/main/java/co/cask/cdap/security/authorization/AuthorizationBootstrapper.java
> +      LOG.info("Admin users specified by {} is empty.", Constants.Security.Authorization.ADMIN_GROUPS);
groups

2017-06-01 06:26 UTC, rohitsinha54 commented on cdap-security-spi/src/main/java/co/cask/cdap/security/spi/authentication/SecurityRequestContext.java
> +   * @return the principal type set on the current thread or PrincipalType.USER if not set
Why do we need this ? Doesn't the SecurityRequestContext represent the logged in user ? Type is  always user no ?

2017-06-01 06:26 UTC, rohitsinha54 commented on cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AuthorizationBootstrapperTest.java
> +    SecurityRequestContext.setUserId(ADMIN_GROUP.getName());
Why set group to userId ? I think you need a mock UserGroupMappingService for the unit test

2017-06-01 20:49 UTC, sreevatsanraman commented
Closing the PR. We will address in 4.3

2017-06-01 20:49 UTC, closed without merging

2017-06-01 20:53 UTC, rohitsinha54 commented
Please don't delete this remote branch.