CDAP-7429 Cleanup shell output for spark-shell on HDP
cdapio/cdap pull request #8893
Opened 2017-05-24 21:27 UTC by wolf31o2

This attempts to use the distribution selection tool (`hdp-select` or `iop-select`) to determine if the `spark-client` is installed and configured or not. This prevents us from attempting to run `spark-shell` on these distributions when we're aware it's not installed and configured.

2017-05-30 20:46 UTC, dereklwood requested changes

2017-05-30 20:46 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +      for __dist in hdp iop; do
how does this work on CDH packages?  pretty sure it will hit the last `else` below and fail to detect spark

2017-05-30 20:46 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +          return 1
how does this work on iop?  Won't the first loop iteration, testing for `hdp`, hit this and return prematurely?

2017-05-30 20:51 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +      for __dist in hdp iop; do
The default for `__spark_shell` is the output from `which spark-shell` (though I do need to redirect stderr away... I'll fix)... on CDH, it never matches. However, there's a bug near here. I'll fix that, also.

2017-05-30 20:51 UTC, wolf31o2 commented on cdap-common/bin/functions.sh
> +          return 1
The first iteration will have this empty, because IOP doesn't have an `hdp-select` utility.

2017-05-31 02:09 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +          return 1
after the new fix... yes

2017-05-31 02:09 UTC, dereklwood approved these changes

2017-05-31 14:00 UTC, merged