CDAP-8871 add docs for audit logging
cdapio/cdap pull request #9011
Opened 2017-06-02 00:13 UTC by yaojiefeng

JIRA: https://issues.cask.co/browse/CDAP-8871

2017-06-02 04:43 UTC, anew requested changes

2017-06-02 04:43 UTC, anew commented on cdap-docs/admin-manual/source/operations/logging.rst
> +- After modification of ``logback.xml``, restart ``cdap-router`` and ``cdap-auth-server`` using the following commands::
Do you want to explain what can be modified?

2017-06-02 04:43 UTC, anew commented on cdap-docs/admin-manual/source/operations/logging.rst
> +- After modification of ``logback.xml``, restart ``cdap-router`` and ``cdap-auth-server`` using the following commands::
Oh I see that follows in the next paragraph. Perhaps just reorder?

2017-06-03 19:05 UTC, sreevatsanraman commented
LGTM

2017-06-03 19:05 UTC, merged