[CDAP-8419] Modifies resource center modal to assume the height of children
cdapio/cdap pull request #9099
Opened 2017-06-12 22:07 UTC by ajainarayanan

- Existing UI had a fixed height for resource center modal 
- Removed `75vh` height for resource center modal + makes entities in resource center modal responsive.

JIRA: https://issues.cask.co/browse/CDAP-8419

2017-06-13 23:19 UTC, tonybach commented on cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
> +        @media(max-width: 992px) {
did you mean to do `max-width: 766px` here? Otherwise it overwrites the css for the two-card layout.

2017-06-13 23:20 UTC, tonybach commented
Without a `height` attribute defined, Market looks like this:

![market](https://user-images.githubusercontent.com/6516002/27108824-37b39e16-5054-11e7-95d6-7f26afcbad37.gif)

2017-06-14 18:27 UTC, elfenheart approved these changes
👍  LGTM

2017-06-14 18:33 UTC, tonybach commented on cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
> +        @media (min-width: 992px) and (max-width: 1200px) {
nit: Maybe change this `min-width` to `993px` now that the `max-width` of the one-entity layout is `992px`? Right now they're both `992px`

2017-06-14 18:33 UTC, tonybach commented
One minor comment, otherwise LGTM 👍

2017-06-14 20:49 UTC, ajainarayanan commented on cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
> +        @media (min-width: 992px) and (max-width: 1200px) {
Have fixed the max-width to be 991px for the next rule.

2017-06-14 22:13 UTC, bdmogal requested changes
@ajainarayanan there seems to be more padding on the right than the left:
![image](https://user-images.githubusercontent.com/3895099/27156890-fb7a9e98-5113-11e7-9dc8-1ef6cbfebabf.png)

![image](https://user-images.githubusercontent.com/3895099/27156908-07e07d7e-5114-11e7-9c24-37df5efe9a1e.png)

2017-06-15 22:47 UTC, bdmogal approved these changes

2017-06-15 22:52 UTC, merged