[CDAP-11636] Add line numbers to dataprep table
cdapio/cdap pull request #9102
Opened 2017-06-13 18:49 UTC by ajainarayanan

- Adds line number column to the left of dataprep table 
- Fixes dataprep table header in firefox (there were issues with borders because of relative positioning of `th` element).

2017-06-13 23:44 UTC, tonybach commented
I think we can use self-closing tags for some of the tags that you just added. Other than that, code LGTM 👍

2017-06-13 23:50 UTC, tonybach commented on cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/UsingPositions/CutDirective.scss
> +        .thead-inverse{
Oh also add a space before the `{`, as currently it causes the build a fail.

2017-06-14 22:02 UTC, bdmogal requested changes
@ajainarayanan let's have the numbers start from 1, not 0.

2017-06-15 21:25 UTC, bdmogal approved these changes

2017-06-15 21:28 UTC, merged