CDAP-6329 Put timestamp in heapdump file name.
cdapio/cdap pull request #9196
Opened 2017-07-06 01:47 UTC by anwar6953

Followup to https://github.com/caskdata/cdap/pull/9135. The change here is to include the date+timestamp (start time of the process) in the file name of the heapdump which is written upon OOM.

![image](https://user-images.githubusercontent.com/2440977/27892039-4de42cf4-61b2-11e7-9cc7-378aadb6b4e3.png)

![image](https://user-images.githubusercontent.com/2440977/27892051-5f6138e6-61b2-11e7-86ef-a63a6e0a2edd.png)

2017-07-06 02:17 UTC, chtyim commented
Why need to provide the exact file name? If it points to a directory, the file name is automatically having pid in there (and the file time is the time).

```
-XX:HeapDumpPath=./java_pid<pid>.hprof | Path to directory or filename for heap dump. Manageable. (Introduced in 1.4.2 update 12, 5.0 update 7.)
```

2017-07-06 03:03 UTC, anwar6953 commented
All of the system services (kafka, auth-server, cdap-master) will be files in the same directory? How will we distinguish then? We'll not have a mapping from pids to service name, right?

2017-07-06 04:21 UTC, chtyim commented
Can't you write to individual directory?? `/var/log/cdap/master/`, `/var/log/cdap/kafka`... etc.

2017-07-06 17:45 UTC, chtyim commented
LGTM as long as it has been tested.

2017-07-06 17:47 UTC, anwar6953 commented
Testing currently...

2017-07-06 18:25 UTC, poornachandra commented
Is there a way to turn the heap dump off?

2017-07-06 18:27 UTC, anwar6953 commented
No, but is there a need? This is only for the system services on the edge nodes, of which there are limited.

2017-07-06 18:34 UTC, poornachandra commented
Silently creating file of few gigs every time an OOM occurs can fill up the disk if it goes unnoticed.

2017-07-06 20:07 UTC, anwar6953 commented
Users can now disable the heap dump on OOM, by putting `HEAPDUMP_ON_OOM=false` in cdap-env.sh.

2017-07-06 20:35 UTC, dereklwood requested changes
Also, need to consider how this will work in CM.  I believe it may already send these flags to dump to a different directory, but need to doublecheck.  If so, that means it's inconsistent, and this new variable will not take effect in the CSD (since cdap_start_java is not called by the CSD).

2017-07-06 20:35 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +  if [ "$HEAPDUMP_ON_OOM" = true ] ; then
``if [[ ${HEAPDUMP_ON_OOM} == true ]]; then``

2017-07-06 20:35 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +cdap_create_dir() { test -d "$1" || mkdir -p "$1"; }
``${1}``

2017-07-06 20:41 UTC, anwar6953 commented on cdap-common/bin/functions.sh
> +cdap_create_dir() { test -d "$1" || mkdir -p "$1"; }
Is that just better practice?
I found "$1" usage here: http://tldp.org/LDP/abs/html/complexfunct.html

2017-07-06 20:44 UTC, anwar6953 commented on cdap-common/bin/functions.sh
> +  if [ "$HEAPDUMP_ON_OOM" = true ] ; then
better practice just to have two brackets?

2017-07-06 20:50 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +cdap_create_dir() { test -d "$1" || mkdir -p "$1"; }
just per style guide: google.github.io/styleguide.  Though it looks like they are actually flexible on positional params... however most of our other scripts use braces for these (and all) variables.

2017-07-06 20:53 UTC, dereklwood commented on cdap-common/bin/functions.sh
> +  if [ "$HEAPDUMP_ON_OOM" = true ] ; then
[[ ]] preferred per style guide: https://google.github.io/styleguide/shell.xml, but you also need ``==``, and variable brace style

2017-07-06 20:57 UTC, anwar6953 commented on cdap-distributions/src/etc/cdap/conf.dist/cdap-env.sh
> +HEAPDUMP_ON_OOM=true
@dereklwood @mattwuenschel I'm not sure why some variables here have `export` and others don't... Any suggestion?

2017-07-06 21:25 UTC, dereklwood commented on cdap-distributions/src/etc/cdap/conf.dist/cdap-env.sh
> +HEAPDUMP_ON_OOM=true
while it's technically not needed, it seems like convention that in hadoop *-env.sh files variables get exported...  So i guess we should also ``export`` them all, for consistency

2017-07-13 02:39 UTC, dereklwood commented on cdap-distributions/src/etc/cdap/conf.dist/cdap-env.sh
> +# Create heapdump upon OutOfMemoryError (true by default)
since the location is not configurable (would be nice to add in the future), maybe just a note here that the CDAP log directory will be used.

2017-07-13 02:40 UTC, dereklwood approved these changes
minor suggestion, otherwise LGTM

2017-07-13 18:48 UTC, anwar6953 commented on cdap-distributions/src/etc/cdap/conf.dist/cdap-env.sh
> +# Create heapdump upon OutOfMemoryError (true by default)
Added a note on the next line.

2017-07-13 18:53 UTC, merged