Feature/ui excel first row header
cdapio/cdap pull request #9616
Opened 2017-09-15 21:00 UTC by bdmogal

Jiras:
[CDAP-11412](https://issues.cask.co/browse/CDAP-11412)
[CDAP-11822](https://issues.cask.co/browse/CDAP-11822)

2017-09-15 21:03 UTC, ajainarayanan approved these changes
👍 LGTM

2017-09-15 21:38 UTC, nitinmotgi commented
LGTM 👍

2017-09-15 21:44 UTC, elfenheart commented on cdap-ui/app/cdap/components/DataPrep/DataPrepTable/DataPrepTable.scss
>          &.dropdownOpened,
these two should be deleted as well

2017-09-15 21:46 UTC, elfenheart requested changes

2017-09-15 21:46 UTC, elfenheart commented on cdap-ui/app/cdap/components/DataPrep/DataPrepTable/DataPrepTable.scss
>          &.dropdownOpened,
These two should be removed as well

2017-09-15 21:48 UTC, bdmogal commented on cdap-ui/app/cdap/components/DataPrep/DataPrepTable/DataPrepTable.scss
>          &.dropdownOpened,
nice. removed.

2017-09-16 01:08 UTC, ajainarayanan reviewed
👍  Unless @elfenheart has any comments.

2017-09-16 06:20 UTC, elfenheart approved these changes

2017-09-18 15:31 UTC, merged